- Simplified/NYPLBasicAuth.m
@aslagle  
This will allow the application to ignore `WWW-Authenticate` headers that are not for basic auth instead of simply giving up.
> Added the ability to handle multiple WWW-Authenticate headers

- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksNavigationController.m
- Simplified/NYPLMyBooksViewController.m
- Simplified/en.lproj/Localizable.strings
disable/enable of Library Switcher Icon improved in My Books and Holds:
- Added completion block to "sync" in catalog nav controller
- No longer relying on bookRegistryDidChange notification. that would fire multiple times and was re--enabling the icon too soon
> Account switching #527

- Simplified/NYPLConfiguration.h
- Simplified/NYPLConfiguration.m
Use OAuth for Desk Support. Call the function that uses OAuth to access Desk Support and remove the function call that uses username and password to access Desk.
Part of the fix for PR https://github.com/NYPL-Simplified/helpstack-ios/issues/1 SSO Refactor (for helpstack-ios repo)
> Use OAuth for Desk Support

- Podfile
Cocoapods issued the following warning on `pod install`:
[!] `xcodeproj` was renamed to `project`. Please update your
Podfile accordingly.
This fix simply implements the above suggestion.
---
If everything looks good, please feel free to merge!
> Fix xcodeproj -> project warning in Podfile

- adobe-rmsdk-build.sh
It seems like building book2png was entirely unnecessary. Doing so also occasionally caused problems because it would fail if the right provisioning profile magic was not in place. I tested this fix with @vuinguyen and it allowed her to get her environment set up properly.
> Make adobe-rmsdk-build.sh no longer build book2png

- Simplified.xcodeproj/project.pbxproj
The SimplyE target was explicitly setting `OTHER_LDFLAGS` to `-ObjC` without use of `$(inherited)`. The lack of `$(inherited)` caused CocoaPods to issue the following warnings:
[!] The `SimplyE [Debug]` target overrides the `OTHER_LDFLAGS` build
setting defined in `Pods/Target Support
Files/Pods-SimplyE/Pods-SimplyE.debug.xcconfig'. This can lead to
problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.
[!] The `SimplyE [Release]` target overrides the `OTHER_LDFLAGS`
build setting defined in `Pods/Target Support
Files/Pods-SimplyE/Pods-SimplyE.release.xcconfig'. This can lead to
problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.
Adding `$(inherited)`, …
> Make CocoaPods not warn about OTHER_LDFLAGS

- Simplified+RMSDK.xcconfig
- Simplified.debug.xcconfig
- Simplified.release.xcconfig
- Simplified.xcconfig
- Simplified.xcodeproj/project.pbxproj
Prior to this commit, we had four `*.xcconfig` files:
* `Simplified.debug.xcconfig`, which just included `Simplified.xcconfig` and `Simplified+RMSDK.xcconfig`;
* `Simplified.release.xcconfig`, which was identical to `Simplified.debug.xcconfig`;
* `Simplified.xcconfig`, which contained the bulk of the project configuration;
* `Simplified+RMSDK.xcconfig`, which included headers for DRM-related libraries and set `FEATURE_DRM_CONNECTOR=1`.
The project was set to use the `Simplified.debug.xcconfig` and `Simplified.release.xcconfig` configurations for debug and release respectfully. The SimplyE target _within_ debug and release was set to use `Simplified+RMSDK.xcconfig`, however.
It was the later portion that caused CocoaPods to issue the following warnings:
[!] CocoaPods did not set the base …
> Make CocoaPods not warn about .xcconfig files

- Podfile.lock
This seems to have gotten lost somewhere along the way. We definitely should be making use of it though: Without it, our builds are not even remotely reproducible.
> Make use of Podfile.lock

- Podfile
- Podfile.lock
- Simplified/software-licenses.html
This patch makes changes to "Podfile.lock" which is not currently in `master`.
**You must merge #573 (which adds "Podfile.lock") before merging this pull request**.
---
This was used for a version of card creator that no longer exists. I removed it as a dependency and removed the license text.
> Cut CHRTextFieldFormatter

- README.md
Most people building without DRM will not have access to the private DRM-related repositories. As such, removing the DRM-related submodules is necessary for the `git submodule update --init --recursive` step to complete successfully.
> Document submodule removal for no-DRM builds

- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderViewController.m
Provides room in header and footer to keep the navigation "shown" while reading page to page. Also places in title and page position into those spaces when the navigation is hidden.
Fixes #470
> Updated Settings/Navigation Toolbar in Reader

- Simplified/en.lproj/Localizable.strings
Changed age verification message to "You must be 13 years of age or older to download some of the books in this collection. How old are you?"  This change is only in the English message.
fixes #541
> Changed confusing age verification message.

- Simplified/NYPLReaderSettings.m
fixes crash by re-adding old keys from text-size in reader settings
> added old keys to text size in reader settings to prevent crash

- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderSettings.h
This fixes a MAJOR memory leak and a major hog of CPU. The app was never releasing `NYPLReaderReadiumView` instances thus causing WebKit processes to pile up. We should get this into a release ASAP.
> Fix leaking of NYPLReaderReadiumView

- Podfile.lock
I feel like this must have gotten accidentally removed from the project somewhere along the way. `Podfile.lock` is necessary for reproducible builds and thus it should always be checked in (as per [the CocoaPods guide](https://guides.cocoapods.org/using/using-cocoapods.html)).
> Add Podfile.lock

- Simplified/NYPLOPDSFeed.m
Added an extra ```defined(FEATURE_DRM_CONNECTOR)``` check to allow the app to build for users without DRM.
Verified in testing to still allow downloads of DRM-free books in SimplyE and NYPL accounts.
This does not effect any development machine with DRM installed.
Fixes #634
> Non-DRM Building

- Podfile.lock
- Simplified/NYPLAccount.m
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLConfiguration.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLMyBooksNavigationController.m
- Simplified/NYPLMyBooksViewController.h
- Simplified/NYPLMyBooksViewController.m
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/Simplified-Info.plist
- Simplified/SimplyE-Bridging-Header.h
Main Features:
- Consolidates Adobe DRM Activation.. Auth and De-Auth to Signing In and Out only. Reducing the number activation steps should eliminate issues with the Adept library; sometimes crashing.
- Licensor Token saving/refreshing (in the loans feed) had to be audited to make sure it was being saved and used at appropriate times, as well as make sure expired tokens are not used.
- In a rare case where a sign out is attempted with an expired token, the app makes a second attempt with a fresh token.. in the background to the user
To the user these changes should:
- Fix a crash around launching the app / credentials / signing in and out
- Reduce number of lost activations for users
- Reduce "download failed" on loans
- No more stuck loans that cannot be returned until they expire
- …
> Drm bug #645 (activation workflow changes)

- Simplified/NYPLAccount.m
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLSettings.h
- Simplified/NYPLSettings.m
Fixes crash caused by a nil parameter. The source of the flow turns out to be from old keychain credentials persisting across app installs. In those cases the device is considered "logged in" but is not actually DRM-authorized with Adobe.
This PR both prevents keychain items from persisting across app deletions and re-installs, and also has a one-time attempt to authorize any devices that are in this current state. It will purge the account if that retry fails, forcing the user to explicitly log back in.
fixes #673 
The related change to the adept submodule:
[PR 12](https://github.com/NYPL-Simplified/DRM-iOS-Adobe/pull/12)
> Bug device auth #673

- Simplified/NYPLMyBooksDownloadCenter.m
Fixes #671 
Prevents unexpected-nil crash. Adds bugsnag report to collect data, and further understand why identifier may get lost when creating NYPLBook from the book registry (based on a valid identifier string).
> Bug book return #671

- Podfile.lock
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLSettingsAccountDetailViewController.m
Continuation of work in:
https://github.com/NYPL-Simplified/Simplified-iOS/pull/641
The UX was re-tested against both master branches.
Resolves #595 
User must now explicitly dismiss the final review screen during Card Creation. PR also removes coupling of main app and the library. Changes to Card Creator repo are merged.
> Card Creator review and modal dismissal

- Simplified/NYPLAnnotations.swift
Fixes #672  crash when accessing headers var getter.
Should resolve bugsnag bug referenced ticket.
Whatever cause of missing credential header, passing an empty field as the fail-case should allow server and networking method to handle error more gracefully.
> Bug annotations #672

- Simplified/NYPLBook.m
- Simplified/NYPLBookAuthor.swift
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLSettingsAccountsList.swift
This PR addresses issue #613 , by allowing library logos that are too small, to scale up to the correct dimensions on the accounts list page
> Allow scaling of logos on accounts list to correct dimensions #613

- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksNavigationController.m
Update UIAlertController's to protect against possible nil that anchors iPad-style ...crashes when presenting.
fixes #704 
3 instances of UIAlertController that could produce this bug; when the visible view controller is cast and ends up being nil, the bar button anchor would not be set, triggering this exact exception and trace.
> UIAlertController popover anchor bug

- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksViewController.m
This PR addresses issue #697 , by hiding the activity indicator after the user dismisses the login prompt on either the My Books or Reservations tab. It also fixes a related problem where, if the user had an account with books, the Collection View would not move up to the top of the screen. In both cases, either an empty View or a Collection View with books now moves up to the top of screen, properly hiding the activity indicator behind it.
> Get pull-to-fresh activity indicator to hide correctly #697

- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksViewController.m
Didn't quite fix the incorrect content offset in My Books and Reservations that was merged as #703 originally from issue #697
> Update content offsets to ensure correct scroll pos. in all scenarios.

- Simplified/NYPLBookDetailViewController.m
Layout does not seem to finalize on viewDidLayoutSubviews. Moving to viewDidAppear to check for height of UITextView.
> Fixed bug with "read more..." label on summary text

- Simplified/NYPLSettingsAccountDetailViewController.m
fixes #709 
Fixes: user could not sign out of an account that had its credentials changed.
> Update account sign out to allow edge case of user-changed credentials.

- Simplified/NYPLReaderReadiumView.m
@gioneill Please merge this after reviewing it as I will be unable to do so. Thank you!
---
The code that hunted around the internals of the web view and removed the callout bar was inadvertently removing more important things on iOS 11. After confirming we no longer need to remove the callout bar at all, I removed the code that deleted it thus fixing the iOS 11 issue and allowing copying, definition lookup, and sharing.
Fixes #646.
> Fix iOS 11 blank pages by keeping callout bar

- Simplified/UIFont+NYPLSystemFontOverride.m
iOS 11 no longer looks to these extension method overrides, so they are being removed to universally use the SF system font across the app.
Custom methods still exist for using text styles and dynamic text.
fixes #710
> Ios11 font override#710

- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLBookCell.m
- Simplified/NYPLBookCellCollectionViewController.m
- Simplified/NYPLBookDetailView.m
- Simplified/NYPLBookDetailViewController.m
- Simplified/NYPLCatalogGroupedFeedViewController.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksViewController.m
- Simplified/NYPLProblemReportViewController.m
- Simplified/NYPLReaderSettingsView.m
- Simplified/NYPLReaderViewController.m
- Simplified/NYPLReportIssueViewController.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSettingsPrimaryTableViewController.m
- Simplified/NYPLSettingsSplitViewController.m
- Simplified/Simplified-Info.plist
Adds split view support to select iPad models. Mostly removes rigid checks on device type and uses the newer trait collection property.
resolves #729
> iPad split view #729

- Simplified/NYPLBookDetailViewController.m
- Simplified/NYPLCatalogGroupedFeedViewController.m
- Simplified/NYPLFacetBarView.m
- Simplified/NYPLProblemReportViewController.m
- Simplified/NYPLReaderViewController.m
More fixes around:
- Split view refactoring
- new iOS 11 auto layout requirements for bar button items
- creating new facet bar init. UIToolbar workaround no longer works in iOS 11
> Ios11 updates

- Simplified/NYPLBookDetailTableView.swift
- Simplified/NYPLSettingsAccountsList.swift
- Re-enabling related works lanes in book detail view
- auto layout improvements to library accounts list.. (looks cleaner and keeps consistent heights for 1 and 2 line subhead descriptions)
> Ios 11 preparations #695

- Simplified/Accounts.json
Just noticed this issue as I was taking screenshots for Carroll County. I assume we originally had 3 as a placeholder and never went back and updated it.
> Changed Alameda's entry ID to 7.

- Simplified/Accounts.json
Adds the authPasscodeAllowLetters and authPasscodeLength where they were not previously in Maryland and Califa libraries. In the iOS client, only Alameda County was found to be missing these fields.
> Add authPasscode fields to Alameda

- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogGroupedFeed.m
- Simplified/NYPLKeychain.m
- Simplified/NYPLOPDSEntry.m
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLOPDSLink.m
This ended up just being an oversight that the client assumed the licensor to exist in a spot where it can be optional.
Also refactored parsing of the Licensor to provide better context to errors in the console.
There was also logic to look for and parse a client token inside the OPDSLink class. This has been removed. Even if a token did exist within a link child of an entry, the client uses the property at the "feed" level so at least we're being consistent in execution now.
Finally, I saw that the `schema:Series` child link was not being parsed correctly.
resolves #788
> Licensor parse bug#788

- Simplified/NYPLSettingsPrimaryTableViewController.m
For some reason the gesture was no longer being recognized in the Navigation Bar in iOS 11, so it's been moved to the footer text label, which is also where it's located on Android.
I think it makes sense to just have an "Advanced" menu at some point as well as auditing to make sure everything still works past the Multi Library changes. Could also put in other things like supporting basic auth. For now though, just this adjustment.
> Move secret gesture recognizer to footer text label

- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksNavigationController.m
...for hiding/showing library switch
The code in viewDidAppear as well as the no-completion return in the book registry created a situation where one library's book registry would copy over into a non-auth library like the SimplyE collection, at the end of a sync.
Also tried to standardize the notifications to eliminate vectors for the app to think it was in the wrong sync state.
fixes #676
> Standardize usage of sync notifications

- Podfile
- Podfile.lock
- Simplified/NYPLCatalogGroupedFeedViewController.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderViewController.m
several top bugnsag crashes addressed:
fixes #824
fixes #825
fixes #826
fixes #827
fixes #828
#670 is not solved, but in order to reduce the user-frustration around the crash, book position is now locally saved every 6 pages forward or backward in the book. Enabling SimplyE Sync in 2.2.0 is also going to dramatically reduce the the loss of reading position.
We still need to solve this crash, but it's a good band-aid for now.
> Stability improvements, Bugsnag Issues Closed

- Simplified/Accounts.json
- Simplified/Simplified-Info.plist
Remove Black Gold Coop until library gives final approval. Approval was pulled at last minute. Continuing release with significant stability enhancements.
Make change to enable Barcode Display for BPL.
> 2.1.3 Release Prep (Remove Black Gold)

- Simplified/NYPLBook.h
- Simplified/NYPLBook.m
- Simplified/NYPLBookButtonsView.m
- Simplified/NYPLBookDetailButtonsView.m
- Simplified/NYPLBookDetailNormalView.m
- Simplified/NYPLOPDSLink.h
- Simplified/NYPLOPDSLink.m
- Simplified/NYPLReaderViewController.m
- Simplified/NYPLRoundedButton.h
- Simplified/NYPLRoundedButton.m
- Simplified/en.lproj/Localizable.strings
fixes #842 
Unifies look to NYPLRoundedButton.
Removes "Clock" icon view from buttons, as well as stubs for "Queue" icon.
Move language into book detail to provide queue and total copies information while a book is in "Reserved" Status.
> Reservation messaging #842

- Simplified/NYPLReaderViewController.m
Remove borders to match a more modern look comparable to other applications. Also will match upcoming PDF reader icons (that don't have borders). Content insets had to be updated to provide even spacing and good visual balance between them.
Icons maintain minimum area recommended by Apple for enough room to tap (44x44 pt).
Feature branch has changes to icons, so PR is not back to master, but should at least provide a way to discuss this or make it visible as a separate feature.
> Update reader icons

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLBarcode.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLZXingEncoder.h
- Simplified/NYPLZXingEncoder.m
- Simplified/SimplyE-Bridging-Header.h
Create Objective-C method wrapper to handle thrown NSExceptions.
Add logging for interest in collecting authorization ID's that are not valid barcode numbers.
Fixes #846
> Handling Exceptions with ZXingObjc

- Simplified/NYPLBarcode.swift
- Simplified/Simplified-Info.plist
Only happening on iOS 11, and cannot currently reproduce. But potential changes to address fix:
- Properly check and request access for the camera.
- Remove a plist key no longer used by the OS. (7.0+)
- Add a plist key for adding photos to the camera roll, as this may be allowed in an unknown dark corner of HelpStack.
Observe Crash analytics for further possible maintenance.
fixes #845
> Privacy Violation Crash (potential fixes)

- Simplified/NYPLBookButtonsView.m
- Simplified/NYPLBookDetailButtonsView.m
- Simplified/NYPLBookDetailNormalView.m
- Simplified/NYPLRoundedButton.h
- Simplified/NYPLRoundedButton.m
Bring back the clock icon view for loan due dates. This was useful contextual information. Keep out the guess for reservation times, since that has been moved to book detail with more information like queue position and total books in circulation for those in line.
> NYPLRoundedButton IconView update

- Simplified/NYPLReaderReadiumView.h
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderRenderer.h
- Simplified/NYPLReaderSettings.h
- Simplified/NYPLReaderSettings.m
- Simplified/NYPLReaderTOCViewController.h
- Simplified/NYPLReaderTOCViewController.m
- Simplified/NYPLReaderViewController.m
- Simplified/Simplified.js
This PR makes numerous improvements:
* Interactive EPUB 3.X content is now more likely to work as intended.
* It is now possible to swipe over a link to turn a page.
* Skeuomorphic page turn animations have been eliminated.
* Crashes related to the juggling of rasterized webviews will no longer happen.
* Crashes related to the use of synchronous JavaScript to detect link locations will no longer happen.
* `NYPLReaderSettings` no longer breaks abstraction boundaries by referencing an instance of `NYPLReaderReadiumView`. The proper plumbing is now handled via delegates.
* Much unnecessary code has been purged.
Closes #858
Closes #576
> Overhaul reader animation and gesture code

- Simplified/NYPLAccount.m
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAnnotations.swift
- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLOPDSFeed.h
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLReaderBookmark.swift
- Simplified/NYPLReaderTOCViewController.m
- Simplified/NYPLReadiumViewSyncManager.m
- Simplified/NYPLSettingsAccountDetailViewController.m
2 new commits to resolve #678 
In a typical user session inside SimplyE Settings, if a user picks a non-active library account (to sign in or change settings), there will likely be several scattered calls to NYPLAccount, and a single call to the singleton "sharedAccount" will rewrite all the global variables and start creating havok with keychain credentials and other values stored in the keychain.
It's too fragile to rely on developer knowledge of this fact, so the class should ultimately be reworked for safety.
The most immediate issue was that credentials would overwrite the current active account creds. So this has been fixed in addition to showing the credentials when re-visiting the particular detail page.
> Bookmark Sync Improvements + NYPLAccount stopgaps

- Simplified/NYPLCatalogGroupedFeedViewController.m
- Simplified/NYPLCatalogUngroupedFeedViewController.m
Protect against nil when trying to cast a collection view cell.
Missed this when updating the GroupedFeedViewController for the same issue before.
Fixes #871
> 3D Touch - Nil Casting Crash Fix

- Podfile
- Podfile.lock
SQLiteSwift library: move off of forked repo and back to main author's library. Min deployment updated with 0.11.4.
Point update contains mostly stability fixes. Initial testing seems fine, and we can continue to monitor [this crash](https://github.com/NYPL-Simplified/Simplified-iOS/issues/897) for any changes.
> SQLite.swift update + move off fork

- Simplified/NYPLReaderTOCViewController.m
> Prevent attempt to access index out of bounds on an array.

- Simplified/NYPLAnnotations.swift
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLCirculationAnalytics.swift
- Simplified/NYPLNetworkQueue.swift
- Simplified/NYPLReachability.h
- Simplified/NYPLReachability.m
- Simplified/SimplyE-Bridging-Header.h
Improves reliability and organization of NetworkQueue in a couple ways:
- Synchronizes an iterator on the sqlite table so that network requests and their completion blocks do not happen on different threads, which is likely to resolve #897 
- Turn NetworkQueue into a singleton instead of fully static class. NYPLReachability doesn't need to "know" about the queue. The instance is created on app launch in the app delegate.
> Offline queue sql fix #897

- Simplified/NYPLOPDSAcquisitionAvailability.m
...to keep reserved and ready books correctly separated.
resolves #916
There may be larger implications to this change that still needs to be addressed, @winniequinn. As far as I can tell, a book entry currently on hold (reserved) would have a "copies available" tag set to equal 0. However, when setting the availability, the conditional would mistakenly set the acquisition to "unavailable".
Later down in execution, when trying to access books in the book registry, `NYPLBookRegistryRecord` would mistakenly set the "state" property of the record to `NYPLBookStateDownloadNeeded` which ends up putting everything in My Books and nothing in the Reservations tab.
> Remove observation of Available Copies when creating OPDS Availability

- Simplified/NYPLBook.m
- Simplified/NYPLCatalogLane.m
- Simplified/NYPLCatalogUngroupedFeed.m
Books that show up in My Books after the registry syncs will still appear even if the client does not support them. This seems like the safest option and it is consistent with the app's historical behavior.
Closes #917.
---
Filtering of books happens in the catalog portion of the app, not in the OPDS parsing portion as it did in older versions of the application. This is correct because the OPDS parser should be ignorant of application-level concerns.
Note that `[NYPLOPDSAcquisition defaultAcquisition]` now returns `nil` instead of choosing an arbitrary acquisition when the app does not support any of the acquisitions available. This behavior probably should have been in place already and it seems like a safe change.
> Filter only supported book formats in the catalog

- Simplified/NYPLOPDSAcquisitionAvailability.m
It is possible to hold a reservation for a book without an available license.
Prior to this commit, we were always chosing with lower number as the hold
position and the higher number as the total copies.
closes #922
It looks like the only place these values are read off `NYPLOPDSAcquisitionAvailability` are in `NYPLBookDetailNormalView` which is where the string is.
> Hold positions are not always lower than total copies

- Simplified/NYPLBookDetailNormalView.m
This indicates that the number of lines should fit the text
closes #936 
on 4 inch phones
on 5.5 inch phones
> Update numberOfLines to 0 for UILabel

- Simplified/NYPLNetworkQueue.swift
- Simplified/NYPLReadiumViewSyncManager.m
resolves #931 
Two Issues addressed:
1. It's likely that sporadic inconsistencies in network reachibility listeners sometimes cause multiple rapid requests to the offline queue, so there's been protection added to only process one call at a time and restricting curther calls until the attempted requests to finish.
2. If a user left a book they were reading, the last queued page position would immediately be requested to be sent off, but it was not correctly clearing that same bookmark on the 30 second rolling queue. So this would cause the same page position to be sent one more time unecessarily.
Further: There's a decent argument to be made for some kind of strategy to mitigate erratic or high frequency changes to the network reachibility notification mechanism, but without further …
> Annotation server fixes

- Simplified/NYPLReadiumViewSyncManager.m
but keep probability of a bad UX low.
fixes #941
> Increase sync manager delay to 60s to reduce server requests,

- Simplified.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
>Xcode 9.3 adds a new IDEWorkspaceChecks.plist file to a workspace’s shared data, to store the state of necessary workspace checks. Committing this file to source control will prevent unnecessary rerunning of those checks for each user opening the workspace.
> Adding new Xcode-generated file for state of workspace checks.

- Simplified/NYPLReaderReadiumView.m
@winniequinn 
Quick inspection apprecated... Occassional crash from trying to send `rangeOfString` to `NSNull` on `result` on line 704.
fixes #986
> Address possibility of NSNull return from a Nullable variable.

- .gitignore
I'm surprised this was never done. Presumably we all had it in our personal ignore files.
> Ignore ReaderClientCert.sig

- Simplified/NYPLReaderReadiumView.m
- Simplified/Simplified.js
The following problems have been solved:
- Tapping when the menu is up no longer toggles the UI.
- Selecting text no longer toggles the UI.
- Selecting text from the edge of the screen no longer turns pages.
- Tapping now reliably clears the menu and text selection.
- Turning a page now dismisses the menu and text selection.
- Copying text now dismisses text selection.
> Fix issues with the reader's menu controller

- Simplified/NYPLAccount.m
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLConfiguration.m
- Simplified/NYPLDirectoryManager.swift
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLMyBooksNavigationController.m
- Simplified/NYPLMyBooksViewController.m
- Simplified/NYPLRemoteViewController.h
- Simplified/NYPLRemoteViewController.m
- Simplified/NYPLRootTabBarController.m
- Simplified/NYPLSettings.h
- Simplified/NYPLSettings.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLWelcomeScreen.swift
Previously, switching an account would reuse the top-level view controller in Catalog. This caused various bugs such as the search button not being correctly set after changing libraries. This commit reworks account switching so that `NYPLCatalogNavigationController` throws away its view controllers and starts fresh with a new one, thus eliminating various problems.
In addition, this commit also moves much accounts-related functionality from `NYPLSettings` to its rightful place in `AccountsManager`.
> Rework account switch; pull accounts from Settings

- APIKeys.swift.example
@objc inference was (thankfully) dropped in swift 4; now must be explicit. This fixes build errors I hit when doing a fresh checkout of the project.
> add objcMembers to fix swift 4/xcode 10 build errors

- Simplified/NYPLBookDetailTableView.swift
This PR addresses the JIRA issue: https://jira.nypl.org/browse/SIMPLY-1482
where long titles in the Recommendations lane of the Book Detail View would overlap with the "More..." link as shown here, in a before screenshot (on an iphone 5s simulator, the smallest simulator that I can run on Xcode 10.1 right now):
I've fixed this so now long titles get truncated with "..." and no longer overlap with the "More..." link, as seen here in the after screenshot, also on an iphone 5s simulator:
> Truncate Long Titles on Recommendations Lane #1482

- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLBookRegistry.h
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogFeedViewController.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksViewController.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLUserNotifications.swift
Cleaned up unnecessary syncs performed from the book registry.
Now only syncs once when the app launches into the foreground/active state.
Utilize background tasks for notifications-related delegates.
> Notifications Refinements

- Simplified/NYPLBookDetailView.m
- Simplified/NYPLBookNormalCell.m
- Simplified/NYPLCatalogLaneCell.m
This prevents cover images from being inverted when using iOS 11's smart invert color feature.
**NOTE:** I was not able to test this change, although I'd be happy to do so if I could receive an up-to-date `Accounts.json`. I'm especially unsure about `blurCoverImageView`.
> Support smart invert colors

- Simplified/Simplified-Info.plist
This PR addresses the following issue: https://jira.nypl.org/browse/SIMPLY-754
where the launch screen layout breaks if the patron's device is displaying the status bar.
This is fixed by hiding the status bar when the launch screen appears. 
Then the status bar, if previously hidden, reappears after the launch screen is gone.
This fix does not affect the launch screen display if the status bar is not displayed.
Tested on iOS 9.3, 10.3.1, 11.3, and 12.1
> Fix Launch Screen When Status Bar is Displayed #754 

- Accounts.json.example
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLReaderReadiumView.h
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderSettings.h
- Simplified/NYPLReaderSettings.m
- Simplified/NYPLReaderSettingsView.h
- Simplified/NYPLReaderViewController.m
- Simplified/NYPLRootTabBarController.h
- Simplified/NYPLRootTabBarController.m
- Simplified/Simplified-Info.plist
- Simplified/Simplified.js
Further refinement of "Frozen Reader" mitigation:
- Only closes reader upon "hitting home button". Does not try and re-open the book.
- Better memory safety around background tasks
- Rate-limit rapid user interaction on reader settings to reduce CFI problems
Further, a possible reproducible state of the "frozen reader" can be achieved by changing font size up and down frequently. However, the UI still responds and the reader can be backed or closed.
> Mitigation (updated)

- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLProblemDocument.h
This PR addresses the issue raised in JIRA #1613: 
https://jira.nypl.org/browse/SIMPLY-1613
where, when a patron tries to check out a book from multiple devices, they will receive an unhelpful error message on the 2nd device.
I try to address this problem by displaying a more useful error message to the patron.
Screenshots for before and after the fix, are in the JIRA issue.
> Display Helpful Error Msg When Borrowing Already Checked Out Book #1613

- README.md
Updated the README with the correct URLs for the `git clone https` lines, and additional instruction for non-DRM build.
> Update build instructions: URLs and non-DRM in README

- Simplified/Accounts.swift
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLSettings.h
- Simplified/NYPLSettings.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLWelcomeScreen.swift
Removing deprecated SimplyE keys being used prior to 2.0(multi-library).
Support for email sign in + any type of keyboard specified by the registry for username and pin fields.
NOTE: Pin == NONE also implies "no pin required". No such implication exists for the username/patron ID field.
Also address issue that caused a new library selection, from a fresh install, to potentially not fully load in until the next app-open.
> Email/Keyboard Support Per Library

- Simplified/BundledHTMLViewController.swift
This fixes a bug where HTML content wasn't shown properly because of the incorrect filtering of links in the NavigationDelegate for the view.  Links in the content will still open in the devices web browser and not in the application.  This replicates the logic that is used in RemoteHTMLViewController.swift.  In other words, the Software Licenses page will show properly.
Alternatives are to render software-licenses.html from an online source and not bundle it with the app.
> Fixed logic in WebViewDelegate to show html content

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLBook.m
- Simplified/NYPLBookAcquisitionPath.h
- Simplified/NYPLBookAcquisitionPath.m
- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLConfiguration.m
- SimplifiedTests/NYPLBookAcquisitionPathEntry.xml
- SimplifiedTests/NYPLBookAcquisitionPathTests.swift
Also, don't crash on book with no valid acquisition paths, and show beta button on Simulator.
On removing the log / throw: I think it's the wrong place to log, since semantically it makes sense that we could ask for the default content type of a book that we don't have a valid acquisition path for. It's also inconsistent, since we would just silently return `NYPLBookContentTypeUnsupported` if we had a path but it was of an unsupported type (which should have already been filtered out before that point). I think if we wanted to log (to bugsnag for instance), it should happen somewhere where we actually don't expect to have an unsupported book.
> Don't show DRM PDFs

- README.md
- Simplified/NYPLBookRegistry.m
- Simplified/SimplyE-Bridging-Header.h
- Updating README to describe more accurately the problem with Carthage when setting up the project
- Removing duplicate bridging header entry
- Invoking `[UIApplication sharedApplication].applicationState` in main thread instead of from background thread
> Minor fixes

- Simplified/NYPLSettingsSplitViewController.m
Minor fix to resolve some issues regarding the view being shown before the viewControllers have been assigned. This was causing warnings to appear primarily when the settings menu was being displayed.
> Fixing warnings on splitview controller

- .gitignore
- README.md
- Simplified/Accounts.json
- Simplified/build_curl.sh
Adding `Accounts.json` to the repo as a commit. This is required for 3.1.x -> 3.2.0 migrations and can be phased out later since we no longer use hardcoded lists.  
The Accounts list has been stripped of most information, leaving only enough for id->uuid mapping.  
The build notes were written with effort to keep enough sensitive info out of the process while making things easier to identify and understand.
> Updating build process

- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLSettingsAccountsList.swift
- Simplified/NYPLWelcomeScreen.swift
- Simplified/en.lproj/Localizable.strings
I couldn't find any instances where I could swap an error message for "disk crashes" or "generic errors" as per https://jira.nypl.org/browse/SIMPLY-2142
> SIMPLY-2142 - Unify error messages for library fetch errors

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLCatalogNavigationController.m
iOS13 changed the default presentation mode for modals from fullscreen to some popping frame. This is an attempt to fix it for "compact" iOS devices (iPhones typically)
> Fixing modal presentation for welcome screen

- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksNavigationController.m
- Simplified/NYPLRootTabBarController.m
While fixing presentation modals, I discovered many issues with calling UI-changing operations on non-main threads. This is considered to put the app in potentially unknown states. It doesn't necessarily crash the app in production but it can produce unpredictable behaviour. It certainly crashes in the debugger.
Most of the changes involve wrapping the calls in question in thread checks
> Fixing execution on non-main threads

- Simplified/NYPLBookRegistry.h
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLUserNotifications.swift
Adds nullability annotations to NYPLBookRegistry.h, eliminating a lot of warnings.
Nullability annotations are essential for proper objc-swift communication. This header file already specified if for a couple members, and when you do that Xcode expects the whole file to deal with annotations.
There are no tests added but I verified every single change is safe.
- i looked at the usage in source files to determine what made sense at runtime. E.g. passing a nil bookmark to `addReadiumBookmark:forIdentifier:` would crash the app.
- i checked usages in swift code of every api/property I modified, in particular `nonnull`s.
- When Swift was not …
> Add full NYPLBookRegistry.h nullability

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLUserNotifications.swift
- Simplified/Utilities/NYPLBackgroundExecutor.swift
- Simplified/Utilities/NYPLMainThreadChecker.swift
1. Simplifies Background Fetch code in app delegate by removing an additional background task (unneeded since we are already in the background, by definition).
2. For background task execution: it makes sure we are ending the task only once.
https://jira.nypl.org/browse/SIMPLY-2072
_Background Fetch_: this is hard to test because we do not control when the app delegate callback is called. My suggestion is to leave a device connected to a Mac and inspect the device logs in Console.app, filtering by "[Background Fetch]". Logs should show something like:
```
[Background Fetch] Starting book registry sync. ElapsedTime=0.1 seconds
[Background …
```
> SIMPLY-2072 Fix background fetch and background execution

- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/xcshareddata/xcschemes/Simplified.xcscheme
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSettingsAccountURLSessionChallengeHandler.h
- Simplified/NYPLSettingsAccountURLSessionChallengeHandler.m
Fixes retain cycles caused by URLSession setup and when executing validating credentials.
https://jira.nypl.org/browse/SIMPLY-2491
While this is not a fix for 2491, memory issues related to network request handling could be cause of hard-to-reproduce bugs. E.g. if the completion closure is living longer that it should, it could keep alive any object that it captured, with unknown side effects.
Since we haven't been able to reproduce the bug on our dev environments, releasing this fix would rule out these known peripheral problems in the code.
This is affecting sign-in flow from the Settings tab only. So hammering on the Settings page signing …
> SIMPLY-2491 Fix retain cycles related to URLSession in Settings tab

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLBugsnagLogs.swift
- Simplified/NYPLConfiguration.h
- Simplified/NYPLConfiguration.m
- Simplified/NYPLDirectoryManager.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderTOCViewController.m
- Simplified/NYPLRemoteViewController.m
- Simplified/NYPLReturnPromptHelper.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLZXingEncoder.m
Replaces all direct calls to Bugsnag with a wrapper call, making NYPLBugsnagLogs (now renamed to NYPLErrorLogger) the only class that depends on Bugsnag.
https://jira.nypl.org/browse/SIMPLY-2583
This is an interim change to ease the upcoming work for actually replacing Bugsnag. This way it's simpler to see how we are using Bugsnag and all we'll need to do to replace it would be to rewrite the calls in NYPLErrorLogger.
It also future-proofs replacing any other future bug/crash reporting tool we want to may use.
At app startup there's a call to report the app launch. Verifying that that even was recorded before and after this change would …
> SIMPLY-2583 Refactor error reporting to Bugsnag wrapper

- README.md
- build-3rd-parties-dependencies.sh
Update the shell script for building 3rd party dependencies
Previous script will give `command not found` error when trying to build
`./build-3rd-parties-dependencies.sh Debug` on `develop` branch
`./build-3rd-parties-dependencies.sh Release` will not build because AudioEngine does not support x86_64 architecture, for detail see [PR#1077](https://github.com/NYPL-Simplified/Simplified-iOS/pull/1077)
No
Yes
@ErnestFan
> Fix scripts to build 3rd party dependencies

- Simplified/NYPLBarcodeScanningViewController.m
Replace deprecated method with modern method
Those methods are deprecated in iOS 6.0
Open barcode scanner in account setting, rotate device and make sure the orientation stays portrait
No
No
@ErnestFan ran this in simulator
> SIMPLY-2590 Replace deprecated method for autorotation

- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/xcshareddata/xcschemes/Simplified.xcscheme
Bumps version number for upcoming release and fixes dSYM submission when archiving.
Brings `develop` up-to-date with correct version we are releasing.
For the dSYMs stuff, I tested it by archiving and checking build logs to verify no errors occurred.
This is just tracking the upcoming release with the correct version number.
Not required.
@ettore
> Bump version to 3.3.6 and fix Firebase dSYM submission

- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLUserProfileDocument.swift
- SimplifiedTests/UserProfileDocumentTests.swift
Throw custom NSError when parsing UserProfileDocument, with unit tests
Log error detail to Crashlytics
[SIMPLY-2491](https://jira.nypl.org/browse/SIMPLY-2491?filter=-1)
Manually tested with dummy data since we are unable to reproduce the error
No
No
@ErnestFan
> [SIMPLY-2491] Handle error when logging in, report error detail to Crashlytics

- Cartfile.resolved
- README.md
- build-carthage.sh
- carthage-update-simplye.sh
Updates to latest NYPL's iOS wrapper for Adobe ADEPT lib and latest Firebase Crashlytics. Also adds a script to run carthage update without errors related to AudioEngine.
Running a normal `carthage update` would inevitably cause errors related to AudioEngine, so I added a little script that can do that and rebuild. The Crashlytics upgrade fixes some occasional linker build issues. The upgrade for the DRM wrapper fixes some warnings that recently popped up.
Not necessary. These are very minor upgrades. I did verify Crashlytics reporting is still working.
No
**Has the application …
> Upgrade to ADEPT wrapper 1.0.2 + minor carthage improvements

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLBookDetailView.m
- Simplified/NYPLConfiguration.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/UIColor+LabelColor.swift
- Simplified/Utilities/UIColor+LabelColor.swift
Refactor the usage of UIColor.label into an extension
See [PR 1096](https://github.com/NYPL-Simplified/Simplified-iOS/pull/1096)
Checked the text color in simulator in both normal and dark mode, nothing changed
No
No
@ErnestFan
> [Refactor] UIColor+LabelColor extension

- Simplified.xcodeproj/project.pbxproj
- Simplified/Account.swift
- Simplified/AccountsManager.swift
This removes a call to the QA library registry if the user is set to use the production library registry. Viceversa, it also removes a call to prod registry when using the QA registry. Essentially, load one or other but never both at the same time. So it should cut library registry times in half.
https://jira.nypl.org/browse/SIMPLY-2663
You can use a proxy to monitor the network traffic and verify the QA library registry is not being hit. If you enable the QA libraries, you should not see the Prod servers being hit.
None.
**Has the application documentation been updated for these …
> SIMPLY-2663 Remove call to QA library registry if using prod

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLReaderSettings.h
- Simplified/NYPLReaderSettings.m
- Simplified/NYPLReaderSettingsView.h
- Simplified/NYPLReaderSettingsView.m
- Simplified/NYPLReaderViewController.m
- Simplified/Reader2/Internal/EPUBModule.swift
- Simplified/Reader2/UI/EPUBViewController.swift
- Simplified/Reader2/UI/NYPLEPUBViewController.swift
- Simplified/Reader2/UI/User Settings/NYPLR1R2UserSettings.swift
- Simplified/Reader2/UI/User Settings/NYPLUserSettingsVC.swift
- Simplified/Reader2/UI/User Settings/UserSettingsNavigationController.swift
- Simplified/SimplyE-Bridging-Header.h
It refactors our reader settings view so that it can be used with the R2 reader. It also makes it so that the settings view opens as a drop-down menu from the top navigation bar on all platforms, and synchronizes font size changes between R1 and R2.
https://jira.nypl.org/browse/SIMPLY-2473
- Open a book from the SimplyE collection that you previously downloaded with R1 (using 3.3.7).
- The book should open with the previously set font size.
- Tapping on the "TT" user settings button on the top right should display our usual UI instead of the one from the R2 test app. 
- Brightness and font size adjustments should work and persist once you …
> SIMPLY-2473 Refactor reader settings view for R2 usage

- Simplified/NYPLBookDetailTableView.swift
- Simplified/NYPLBookDetailsProblemDocumentViewController.swift
Fixes up a missing alert when attempting to report a problem doc.
https://jira.nypl.org/browse/SIMPLY-2677
Somehow trigger a problem document for a book and then attempt to view and report the problem document.
n/a
n/a
@kyles-ep  for the alert but not for the email sending dialog because I don't have a physical device.
> [SIMPLY-2677] Fixing incomplete implementation from SIMPLY-2339

- Simplified.xcodeproj/project.pbxproj
- Simplified/Account.swift
- Simplified/AccountsManager.swift
- Simplified/NYPLAccount.h
- Simplified/NYPLAccount.m
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLBookRegistryRecord.m
- Simplified/NYPLBookState.swift
- Simplified/NYPLDirectoryManager.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/String+MD5.swift
- SimplifiedTests/NYPLBookStateTests.swift
- SimplifiedTests/String+NYPLAdditionsTests.swift
This adds user barcode (one-way hashed) tracking to Crashlytics to more easily diagnose hard-to-reproduce errors happening in the wild. Also adds a lot more logging related to account management. Fixes a couple differences accidentally introduced in 3.3.7 related to BookState handling.
https://jira.nypl.org/browse/SIMPLY-2691
It's unlikely this change actually fixes the issue, plus we never got a clear set of reproducible steps. To test the additional logging and user tracking:
- sign in to a library with your barcode, browse around, sign into different libraries etc.
- ask me to compute the hash for your barcode(s)
- Load the Firebase …
> SIMPLY-2691 More Crashlytics logging and fix a couple minor regressions

- Simplified.xcodeproj/project.pbxproj
- Simplified/AccountsManager.swift
- Simplified/NYPLBookRegistryRecord.m
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLSession.h
- Simplified/NYPLSession.m
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Utilities/URLRequest+NYPL.swift
When executing NYPLOPDSFeed requests now we capture more error situations that would have led to harder-to-diagnose parsing errors. For example the server returns 500s with non-nil plain text data but a nil error (somehow URLSession does not create it in this situation): previously we would have continued and tried to process the returned data, failing with a cryptic parse error.
This PR also improves searchability in Crashlytics by using our Context strings as `domain` for NSErrors that it creates, instead of always using "org.nypl.symplye". However CL allows searching only for error domain and code, so a constant domain string is meaningless.
https://jira.nypl.org/browse/SIMPLY-2695
**How should this be tested? …
> SIMPLY-2695 More logging for OPDS requests + better log searchability

- build_curl.sh
Normalizes curl builds to exclude idn2
My dev environment had idn2 installed and the curl config picked it up and tried to link it. This will ensure such variations won't happen with our curl builds.
Ensure the project builds and works
No
n/a
@kyles-ep
> Standardizing curl build without idn2

- Simplified/NYPLSettingsAccountDetailViewController.m
Fixes a memory leak related to missing invalidating the URLSession in NYPLSettingsAccountDetailViewController.
This was introduced back in February but was should/could have been fixed in SIMPLY-2765.
Not really visible to the user, but stopping the memory debugger after going to a library account page in Settings, then going back, should not show living instances of NYPLSettingsAccountDetailViewController.
Should be included in upcoming 3.4.0.
n/a
@ettore
> Invalidate URLSession and fix memory leak

- Cartfile
- Cartfile.resolved
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSignInBusinessLogic.swift
- Simplified/NYPLUserAccount.swift
Uses the authorization_identifier to source the barcode to provide to the juvenile-creation APIs.
The barcode field in NYPLUserAccount may contain either a barcode or the username, but the Platform APIs for juvenile accounts require to specify what you're passing in (either a barcode or username), but we on the client don't know what the user has signed in with.
For NYPL accounts, and only for NYPL Accounts, the NYPLUserAccount::authorization_identifier instead always contains a barcode: this can be a 14-digit NYPL-issued barcode, or a 16-digit NYC ID (issued by the city of NY). This was confirmed by @leonardr.
Assuming you verified the …
> Use authorization_identifier for juvenile APIs

- Simplified.xcodeproj/project.pbxproj
- Simplified/NSDate+NYPLDateAdditions.h
- Simplified/NSDate+NYPLDateAdditions.m
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLReadiumBookmark.swift
- Simplified/Reader2/Internal/LibraryService.swift
- Simplified/Reader2/Internal/R2+NYPLAdditions.swift
- Simplified/Reader2/Internal/ReaderModule.swift
- Simplified/Reader2/NYPLR2Bookmark.swift
- Simplified/Reader2/NYPLReaderExtensions.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- Simplified/Reader2/UI/NYPLEPUBViewController.swift
Reads a preexisting bookmark from R1 and jumps to the correct position in R2.
https://jira.nypl.org/browse/SIMPLY-2801
Too early for QA testing, this is just a subtask of a larger story. But essentially, bookmark something in R1, then open same book in R2 (you'll have to change the code in `NYPLBookCellDelegate::openEPUB:`) and select the bookmark. 
merging to feature branch.
yes, inside the code.
@ettore
> SIMPLY-2801 Jump from a pre-existing R1 bookmark to R2 position

- Simplified/NYPLAlertUtils.swift
- Simplified/NYPLRoundedButton.h
Adds nullability annotations to NYPLRoundedButton and improves code readability in one of our alert methods.
Objc Nullability is important when interoperating with Swift. I looked at all code paths where NYPLRoundedButton is used between objc-swift.
There's no specific QA steps here, beside some exploratory testing in relation to bookmarking.
Not releasing to prod right now.
Yes.
@ettore
> Add nullability to NYPLRoundedButton + swiftier alert method

- Simplified/NYPLBookRegistry.h
- Simplified/Reader2/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- Simplified/Reader2/UI/NYPLReaderPositionsVC.swift
Removes a bookmark from the business logic / UI objects. It considers 2 flows: 
1. from drop down list in TOC
2. from right-most icon when it's lit up to signify we are positioned on a bookmarked page.
Does not persist bookmarks on server, for that see SiMPLY-2804. 
https://jira.nypl.org/browse/SIMPLY-2803
Might be good to test once the parent story SIMPLY-2608 is complete.
Other than that:
1. add a bookmark, verify it's added
2. re-tap on the same icon to remove bookmark. verify it's removed by opening TOC/bookmarks dropdown.
3. add another bookmark
4. open the dropdown list, and swipe to remove.
**Dependencies for merging? Releasing to …
> SIMPLY-2803 Implement bookmark removal functionality

- Simplified/Account.swift
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAlertUtils.swift
- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLRemoteViewController.m
- Simplified/NYPLSession.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSignInBusinessLogic.swift
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/String+MD5.swift
I did a review of both Sign In VCs and logged every single error that can originate from both.
Also made sure to log the (hashed) barcode since it won't be otherwise available in Crashlytics if sign-in fails.
All errors logged to Crashlytics are now wrapped in a new NSError we generate and log, instead of logging the original error. This should make it more obvious which parts of the app are affected instead of (for example) seeing a generic "Request timeout" error in Crashlytics.
Also, this PR adds an alert before performing sign-out to warn the user that book downloads/returns authorizations or book registry syncing is in progress.
https://jira.nypl.org/browse/SIMPLY-2843
https://jira.nypl.org/browse/SIMPLY-2857 …
> SIMPLY-2843 Log every sign in/out error + provide better user messages

- Simplified.xcodeproj/project.pbxproj
- Simplified/Account.swift
- Simplified/AccountsManager.swift
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLCatalogSearchViewController.m
- Simplified/NYPLDirectoryManager.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLReaderViewController.m
- Simplified/NYPLReloadView.m
- Simplified/NYPLRemoteViewController.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSettingsAccountsList.swift
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/SimplyE-Bridging-Header.h
- Simplified/UIView+NYPLViewAdditions.h
- Simplified/UIView+NYPLViewAdditions.m
- Simplified/Utilities/NYPLBook+Additions.swift
- Simplified/Utilities/URLResponse+NYPL.swift
SIMPLY-2843: In case the catalog fails to load because of a nil URL, the catalog screen will now try to reload both the library accounts list and the current library authentication document. 
SIMPLY-2843, SIMPLY-2853: In case the library accounts list fails, the Settings screen would appear empty and the user would be stuck in the water. This PR adds a Reload button to allow the user to recover from that.
SIMPLY-2857: Adds extensive logging for book download errors.
https://jira.nypl.org/browse/SIMPLY-2843
https://jira.nypl.org/browse/SIMPLY-2853
https://jira.nypl.org/browse/SIMPLY-2857
The easiest way would be to use a proxy and rewrite the …
> SIMPLY-2843, SIMPLY-2853, SIMPLY-2857: Recover from errors on Catalog and Accounts pages

- Simplified/NYPLCatalogFeedViewController.m
- Simplified/Network/NYPLNetworkResponder.swift
Fixes one error logging where we could pass a nil string to a Swift non-optional, and secondly a lock that was not unlocked in case a `guard` was hit.
Avoid potential error situations/crash.
No real testing is actually needed. These are low level bugs.
merging to hot fix branch.
N/A
@ettore
> Fix potential crash and deadlock in network error handling

- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/xcshareddata/xcschemes/Simplified.xcscheme
- Simplified/AccountsManager.swift
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAlertUtils.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLProblemDocument.swift
- Simplified/NYPLRemoteViewController.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/Network/NYPLNetworkExecutor.swift
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Network/NYPLUserFriendlyError.swift
- Simplified/Utilities/URLResponse+NYPL.swift
Centralizes the parsing of Problem Documents in our new network layer. The Problem Document info is returned up in additional `userInfo` keys (per NYPLUserFriendlyError protocol) added to the NSError passed in the completion closure. 
It also simplifies the flow of the error handling code in the Sign In VCs.
https://jira.nypl.org/browse/SIMPLY-2881
Currently the network layer is only used to load the libraries list and the authentication document, but in both cases the calling code does not need to present a detailed error to the user. So this is mainly an infrastructure change. We should still verify that libraries loading and sign in is not …
> SIMPLY-2881 Add parsing of Problem Documents in network layer

- Simplified/AccountsManager.swift
- Simplified/NYPLAgeCheck.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
Puts all accesses to the `AccountManager::accountSets` dictionary behind a concurrent queue using a barrier for write operations to ensure thread-safety for that dictionary.
https://jira.nypl.org/browse/SIMPLY-2846
This crash happened while _reading_ from the dictionary, with a BAD_ACCESS exception reading from 0x0 address. Since that dictionary is on AccountManager, which is a big Singleton class, it can be accessed in R/W mode from many threads, leading to possible memory corruption.
This crash was hard to reproduce so I don't have clear steps on how to do that. I think QA should focus on doing a testing on the sign-in/sign-out flows, …
> SIMPLY-2846 Access shared accounts dictionary in a thread-safe way

- Simplified/AccountsManager.swift
- Simplified/NYPLCatalogFeedViewController.m
- Simplified/NYPLSettingsPrimaryTableViewController.m
Fixes the method signature of a NSNotificationCenter callback, which must include one and only one parameter of type NSNotification. This was broken in a recent refactor. I also fixed some undefined (and eventually unrelated) behaviors I found while debugging.
https://jira.nypl.org/browse/SIMPLY-2930
See steps in ticket.
This can go out after 3.5.0 since it only applies to a hidden feature.
N/A
@ettore
> SIMPLY-2930 Fix crash caused by incorrect notification callback signature

- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksNavigationController.m
Ensures we do have a barButtonItem to use as anchor when presenting an alert view controller in sheet presentation style.
https://jira.nypl.org/browse/SIMPLY-2933
This crash seems to be happening only on iPads on iOS 9 and sometimes 10. I looked at the code at where we use alert sheets and they are in these locations:
- accounts settings page, click on Add Library button
- switching library in Catalog, MyBooks, Holds tabs
- select a sort option in catalogs/my books/holds tabs
none, this will go in 3.5.1 or whatever is next
**Has the application documentation been updated for these …
> SIMPLY-2933 Ensure presence of barButton anchor when presenting sheet

- Simplified/Reader2/AdobeDRM/AdobeDRMContainer.mm
The new code for using Adobe DRM on R2 introduced some warnings. This silence them, since they are all in Adobe's libraries.
https://jira.nypl.org/browse/SIMPLY-2886
No testing needed, since no real changes are added.
merging to feature branch
n/a
@ettore
> SIMPLY-2886 Mute warnings related to Adobe DRM lib

- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAppDelegate.m
- Simplified/NYPLBookDetailTableView.swift
- Simplified/NYPLBookRegistry.h
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLCatalogFeedViewController.m
- Simplified/NYPLCatalogGroupedFeedViewController.m
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLCatalogUngroupedFeed.m
- Simplified/NYPLCatalogUngroupedFeedViewController.m
- Simplified/NYPLHoldsViewController.m
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLMyBooksViewController.m
- Simplified/NYPLOPDSFeed.h
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLOpenSearchDescription.h
- Simplified/NYPLOpenSearchDescription.m
- Simplified/NYPLSession.h
- Simplified/NYPLSession.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSignInBusinessLogic.swift
Wipes the cache contained inside NYPLSession when user pulls-to-refresh by parametrizing the api calls with a "refersh" parameter.
One gotcha: because NSURLCache::removeCachedResponseForRequest: has a bug, it's impossible to reliably remove only the response related to a given request. Since the same class (NYPLSession) handles requests for MyBooks, Holds, book details page, search, ungrouped feeds, invalidating the cache for one of those pages will also wipe the cache all others.
https://jira.nypl.org/browse/SIMPLY-2953
1. install 3.5.1
2. route device network traffic via Charles.
3. sign in into any library, put some books in My Books.
4. …
> SIMPLY-2953 Wipe MyBooks/Holds/book details cache when pulling to refresh

- Simplified/NYPLMyBooksDownloadCenter.m
This is an PR to integrate changes in the Overdrive processor framework that now makes sure to return header keys that are always lowercased. This will ensure better reliability across different library servers that may return headers that are capitalized in different ways. E.g. some servers may return header keys such as `X-Overdrive-Scope` and others `x-overdrive-scope`.
https://jira.nypl.org/browse/SIMPLY-2984
make sure to download Overdrive audiobooks from NYPL and then RoundRock library and Houston. They should all work consistently.
In accordance with Product, we'll merge this to …
> SIMPLY-2984 Use lowercase keys when reading Overdrive headers

- Simplified.xcodeproj/project.pbxproj
- Simplified/Models/NYPLBookContentType.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLMyBooksDownloadInfo.h
- Simplified/NYPLMyBooksDownloadInfo.m
- Simplified/NYPLOPDSFeed.m
- Simplified/Utilities/NYPLBook+Additions.swift
Expose a more detailed reason of error in the summary of the Crashlytics report (which coincides with the `NSError.domain`) and use `NSError.errorCode` as a way to group related errors together. 
E.g. all the business-logic-related book download errors now have the same error code, but the `context` aka NSError.domain will expose the distributor, the book medium  and reason of the error. This will create a larger number of non-fatal "issues" in Crashlytics but each one will contain less instances. This also addresses the fact that it's not possible to link to one event instance inside the same "issue"/group.
https://jira.nypl.org/browse/SIMPLY-2975
**How should this be tested? / Do these changes have associated …
> SIMPLY-2975 Surface rationale of download errors in Crashlytics reports

- Simplified/Account.swift
- Simplified/AccountsManager.swift
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLAlertUtils.swift
- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLBookDetailViewController.m
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLBookRegistryRecord.m
- Simplified/NYPLCatalogFeedViewController.m
- Simplified/NYPLCatalogGroupedFeedViewController.m
- Simplified/NYPLCatalogUngroupedFeedViewController.m
- Simplified/NYPLDirectoryManager.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/NYPLReaderTOCViewController.m
- Simplified/NYPLRemoteViewController.m
- Simplified/NYPLSession.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/NYPLSettingsAccountsList.swift
- Simplified/NYPLSignInBusinessLogic.swift
- Simplified/Network/NYPLNetworkResponder.swift
- replaces some error logging methods with more generic ones that allow more details available at the call site to be logged.
- Updates the terminology to use "Summary" instead of "Context" because this matches better what's seen on Crashlytics.  After using Crashlytics for a while we've seen that grouping too many error instances (with different error reasons) under the same "context" makes it very hard to find a specific error reason. The word Summary in the log method signatures encourages more clearly to provide a more focused title to the error report.
https://jira.nypl.org/browse/SIMPLY-2992
This shouldn't need any more QA than what's …
> SIMPLY-2992 Reorg error logger functions

- Simplified/AccountsManager.swift
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLSignInBusinessLogic.swift
- Simplified/Network/NYPLNetworkResponder.swift
Reports situations such as timeouts and connection drops separately from "real" app errors to make browsing of error reports more straighforward and efficient in Crashlytics.
https://jira.nypl.org/browse/SIMPLY-2985
Covered by regression, since this is an infrastructure change.
n/a
yes
@ettore
> SIMPLY-2985 Group warnings in separate Crashlytics reports

- Simplified/NYPLSettingsAccountDetailViewController.m
Display barcode number on account detail
[SIMPLY-2904](https://jira.nypl.org/browse/SIMPLY-2904?filter=-1)
Log into one of the libraries that support barcode display(eg. NYPL), and click "Show barcode"
A barcode image and number should show up
N/A
N/A
@ErnestFan
> SIMPLY-2904 Display barcode number

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLCatalogNavigationController.m
- Simplified/NYPLConfiguration.h
- Simplified/NYPLConfiguration.m
- Simplified/NYPLKeychain.m
- Simplified/NYPLKeychainManager.swift
- Simplified/OpenEbooks/Resources/OEImages.xcassets/ColorBackground.colorset/Contents.json
- Simplified/Settings/NYPLConfiguration+SimplyE.swift
- Simplified/Tutorial/OETutorialChoiceViewController.swift
- Simplified/Utilities/NYPLPresentationUtils.swift
Fixes the look and feel of the sign in panel for Open eBooks, using color settings in the xcassets and moving out some configuration related to only SimplyE. It also addresses some keychain warnings observed during launch of OE.
https://jira.nypl.org/browse/SIMPLY-3059
This is just a subtask, no need to test at this point.
Not a breaking change for SimplyE.
yes
@ettore
> SIMPLY-3059 Fix OE sign-in panel

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NSNotification+NYPL.swift
- Simplified/AppInfrastructure/NYPLAppDelegate+OE.swift
- Simplified/AppInfrastructure/NYPLAppDelegate+SE.swift
- Simplified/AppInfrastructure/NYPLAppDelegate.h
- Simplified/AppInfrastructure/NYPLAppDelegate.m
- Simplified/AppInfrastructure/NYPLConfiguration+OE.swift
- Simplified/Catalog/NYPLCatalogNavigationController.m
- Simplified/NYPLAccountSignInViewController.m
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksNavigationController.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/OpenEbooks/Resources/OpenEBooks_OPDS2_Catalog_Feed.json
- Simplified/Settings/NYPLSettings+OE.swift
- Simplified/Settings/NYPLSettings+SE.swift
- Simplified/Settings/NYPLSettings.swift
- Simplified/Settings/NYPLSettingsSplitViewController+OE.swift
- Simplified/SimplyE-Bridging-Header.h
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
The AppDelegate and NYPLSettings have/will have similarities and differences between SimplyE and Open eBooks. Previously we dealt with these via ugly #ifdefs. This refactors the differences in separate files that are compiled or not depending on the target.
Other minor things:
- one notification name that will be needed for Clever authentication was expressed via duplicated string literals, which are error prone. Refactored that into a constant.
- Catalog, My Books and Holds navigation controllers have largely identical switchLibrary logic. Before refactoring it to remove this duplication (actually, triplication) I'm doing an intermediate step here.
https://jira.nypl.org/browse/SIMPLY-3091
**How should this be …
> SIMPLY-3091: refactor AppDelegate and NYPLSettings

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NYPLLibraryNavigationController.h
- Simplified/AppInfrastructure/NYPLLibraryNavigationController.m
- Simplified/Catalog/NYPLCatalogNavigationController.h
- Simplified/Catalog/NYPLCatalogNavigationController.m
- Simplified/NYPLHoldsNavigationController.h
- Simplified/NYPLHoldsNavigationController.m
- Simplified/NYPLMyBooksNavigationController.h
- Simplified/NYPLMyBooksNavigationController.m
The common "switchLibrary" logic (shared verbatim by the Holds and MyBooks nav controllers, and minimally differently in the Catalog nav controller) is now moved to a common superclass NYPLLibraryNavigationController.
The moved code does not have any changes whatsoever. Just a cut and paste. Similar story for `setNavigationLeftBarButtonForVC ` and `updateCatalogFeedSettingCurrentAccount`.
This also fixes the build for SimplyECardCreator target in a separate commit.
There's no ticket for this but I noticed this code "triplication" while working on SIMPLY-3091 and I couldn't bear to see that any longer. The superclass solution is not super great either but it was quick, and it's definitely better than before, so in …
> Refactor switchLibrary functionality removing code triplication

- Simplified/AppInfrastructure/NYPLLibraryNavigationController.m
- Simplified/Catalog/NYPLCatalogNavigationController.m
- Simplified/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/WelcomeScreen/OETutorialChoiceViewController.swift
- Simplified/WelcomeScreen/OETutorialEligibilityViewController.swift
- Simplified/WelcomeScreen/OETutorialWelcomeViewController.swift
Disables Copy action in contextual menu inside the eReader for OE. SimplyE is not affected.
Unrelated (in separate commits): fix fonts in OE tutorial and fixed a possible crash I observed in some cases for nil dictionary values.
https://jira.nypl.org/browse/SIMPLY-3101
Open eReader for OE. Hold press on a word. On iOS 11+ you should not see the Copy option. On iOS <= 10 you will see it, but if you select it nothing should be copied.
Copy should still be available on SimplyE on all versions of iOS.
Non breaking for SimplyE
**Has the application documentation been updated for these …
> SIMPLY-3101: Disable Copy action for Open eBooks in eReader

- .gitignore
- Cartfile
- Cartfile.resolved
- README.md
- Simplified.xcodeproj/project.pbxproj
- build-3rd-parties-dependencies.sh
- build-carthage.sh
- carthage-update-simplye.sh
Upgrade AudioEngine from 6.1.15 to 6.5.2
Update build scripts and documentations for fetching AudioEngine
[SIMPLY-3040](https://jira.nypl.org/projects/SIMPLY/issues/SIMPLY-3040)
Run the script `./build-carthage.sh` then build and run the SimplyE
Merge `NYPLAEToolkit` and update the `Cartfile` and `Cartfile.resolved` after approval from QA
Updated README to better describe the build process
@ErnestFan
> SIMPLY-3040 AudioEngine upgrade

- Simplified.xcodeproj/project.pbxproj
- update-certificates.sh
Sets up Crashlytics for OE using its own account on Firebase.
https://jira.nypl.org/browse/SIMPLY-2662
Using the app for a while should trigger events in Crashlytics for OE. I am however taking care of that, so for QA there's not much to do here I think.
make sure to pull from Certificates repo and run the new line in the `update-certificates.sh` script so that the app can build.
n/a
@ettore
> SIMPLY-2662 Set up Crashlytics for Open eBooks

- Simplified/NYPLBookAcquisitionPath.h
- Simplified/NYPLBookAcquisitionPath.m
Adds support for books with `Content-type` of `application/octet-stream`.
Columbia University Libraries - Demo books fail to download because of that unsupported content type.
https://jira.nypl.org/browse/SIMPLY-3153
Open Columbia University Libraries - Demo library and download "Mathematical Theory of Advanced Computing"
No
No
@vladimirfedorov
> SIMPLY-3153 Added support for books with content-type of application/octet-stream

- OpenEbooks/eula.html
- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NYPLAppDelegate+OE.swift
- Simplified/AppInfrastructure/NYPLAppDelegate.m
- Simplified/NYPLOPDSFeed.m
- Simplified/WelcomeScreen/NYPLEULAViewController.swift
- scripts/update-certificates.sh
Displays the EULA at the first launch of Open eBooks. Some of this code was taken/adapted from [Kyle's original OE PR](https://github.com/NYPL-Simplified/Simplified-iOS/pull/1070/files).
Also fixing a newly introduced crash and a miss on the set-up scripts from a recent PR.
https://jira.nypl.org/browse/SIMPLY-3052
1. Install OE from the store (1.8.1) and sign in or at least accept EULA.
2. Now install new OE (1.9.0). You should not see the EULA.
3. Sign out and remove any previous installation of OE. 
4. Fresh install OE, launch it: the EULA should be displayed before anything else.
5. Accept EULA and force quit the app. 
6. Reopen it: you …
> SIMPLY-3052 Show EULA on 1st launch for OE

- Simplified.xcodeproj/project.pbxproj
- Simplified/ErrorHandling/NYPLAlertUtils.swift
- Simplified/ErrorHandling/NYPLProblemDocument.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLOPDSFeed.m
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Network/NYPLRemoteViewController.m
- Simplified/Network/NYPLUserFriendlyError.swift
Displays the contents of the problem document (which are supposed to be user-friendly) when borrowing fails instead of the generic "borrow failed" error message.
https://jira.nypl.org/browse/SIMPLY-3179
Borrow enough audiobooks (esp from Overdrive) so that you reach your loan limit. You should now see an error message that explains that you reached your loan limit, instead of the generic "borrow failed" that we have in 3.6.0.
n/a
yes
@ettore
> SIMPLY-3179 Surface problem document content for borrowing errors

- Simplified/NYPLAnnotations.swift
- Simplified/NYPLBookCellDelegate.m
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
Fixes mentions of the app name in relation to the target being built.
https://jira.nypl.org/browse/SIMPLY-3168
Fresh install the app, sign in and go to the settings screen. If you never enabled Bookmarks Syncing an alert should pop up. This alert should not reference SimplyE.
none
yes
@ettore
> SIMPLY-3168 Mention correct app name for each target

- Simplified/SignInLogic/NYPLAccountSignInViewController.h
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
Refactors static function to present Sign In modal to be non-static, so that the Sign In VC instance can be customized before presentation. This change here has no functional changes: the new `presentUsingExistingBarcode: authorizeImmediately:completionHandler:` is functionally identical to the old `requestCredentialsUsingExistingBarcode:authorizeImmediately:completionHandler:` beside adapting for not being a class method anymore.
This is needed for the work on universal links. 
https://jira.nypl.org/browse/SIMPLY-3092
For regressions, opening the sign in modal should work the same as before.
**Dependencies for merging? Releasing to …
> SIMPLY-3092 Refactor to allow customization before presenting sign-in modal

- Simplified/Accounts/Library/AccountsManager.swift
- Simplified/Accounts/User/NYPLUserAccount.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
3 things (see commits):
- refactors the duplicated logic for updating the user account after signing in. This was duplicated in Sign in VC modal and Sign In VC in Settings tab.
- Sign in VC modal had a retain cycle
- Both Sign In VCs have calls to completely block user interactions during sign in. This is dangerous and deprecated, especially because these calls are not balanced! So I removed most of them because they are more harmful than useful, except one were it's easy to see the balancing.
this refactor is needed for facilitating https://jira.nypl.org/browse/SIMPLY-3092
but the real ticket is https://jira.nypl.org/browse/SIMPLY-2510
There …
> SIMPLY-2510 Refactor account update logic into swift, fix a retain cycle + bug locking up sign-in modal UI

- OpenEbooks/OpenEbooks.entitlements
- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NSNotification+NYPL.swift
- Simplified/AppInfrastructure/NYPLAppDelegate+OE.swift
- Simplified/AppInfrastructure/NYPLAppDelegate.h
- Simplified/AppInfrastructure/NYPLAppDelegate.m
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/Settings/NYPLSettings+OE.swift
- Simplified/Settings/NYPLSettings+SE.swift
- Simplified/Settings/NYPLSettings.swift
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+OAuth.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/NYPLSignInViewController+OESelectAuth.swift
- Simplified/WelcomeScreen/OETutorialChoiceViewController.swift
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
- SimplifiedTests/Mocks/NYPLUniversalLinksSettingsMock.swift
- SimplifiedTests/NYPLSignInBusinessLogicTests.swift
- Add new entitlement only for OE because we are in the process of shipping a new release and we should not change how SE is set up right now.
- Add NYPLIsSigningIn notification to address a bug in OE where the login choice picker would show up after redirection from Clever.
- Avoid tight coupling in NYPLSignInBusinessLogic via NYPLUniversalLinksSettings protocol.
- Add sign-in VC convenience initializer based on OE login choice, using refactor done recently in PR#1217.
https://jira.nypl.org/browse/SIMPLY-3092
I used the sandbox school district  from here: https://github.com/NYPL-Simplified/operations/wiki/TestCardsOpenEbooks#clever
You can …
> SIMPLY-3092 Fixes for Clever authentication in Open eBooks

- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLBasicAuth.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- First refactors (in objc) the construction of sign in/sign out request in Setting tab VC. This also removes an erroneous `if` introduced in the previous PR that was hiding a sign-out error that was preventing Adobe device deactivation.
- Then refactors that to swift in the NYPLSignInBusinessLogic class, this way refactoring also the request-creation logic from NYPLAccountSignInViewController.
- Adds documentation after [chatting](https://librarysimplified.slack.com/archives/CKC8S59NJ/p1602882778082000?thread_ts=1602871744.079100&cid=CKC8S59NJ) with @gioneill and @io7m about why we need to issue a sign out request that is really a sign-in request: this is because we need a fresh Adobe token to successfully deactivate the Adobe device.
**Why are we doing this? (w/ JIRA …
> SIMPLY-3092 Refactor sign in + sign out requests to Business Logic class

- Simplified/NYPLReadiumBookmark.swift
- Simplified/Reader2/NYPLBookmarkR2Location.swift
- Simplified/Reader2/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
Fixing a bug of bookmark create failed in R2 reader
Also fix the double "Ok" on the fail alert
Note:
There is a bug navigating to the bookmark in R2 reader.
The readium team has located this issue and has a PR opened for it. [PR link](https://github.com/readium/r2-navigator-swift/pull/142)
We need to upgrade our r2-navigator once they have this issue fixed.
[SIMPLY-2820](https://jira.nypl.org/browse/SIMPLY-2820)
Open a book that never been open in R1, create a bookmark and check if it exist in the bookmark list
N/A
N/A …
> SIMPLY-2820 Fix R2 bookmark create bug

- Simplified/Accounts/User/NYPLUserAccount.swift
Background: since at least v3.3.5 and probably earlier, user info is stored in the keychain using keys whose names have the library UUID appended to the "raw" key name (such as "barcode"). One exception is the NYPL account, for which historically the library UUID has not been appended.
Recent SAML code (shipped in 3.6.0) added the `NYPLUserAccount::libraryUUID` property, used to set the key names only once instead of each time we need to read the `NYPLUserAccount::sharedAccount` computed property, and also to get the `authDefinition` property. However this code also introduced a regression (checkin 92ff20c) by defaulting to `nil` the libraryUUID for NYPL, which leads to wrong `authDefinition` values.
This fix restores the original intention, leaving nil-handling only …
> SIMPLY-3219 Unable to see NYPL sign-in info

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/SimplyE-Bridging-Header.h
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSAMLHelper.h
- Simplified/SignInLogic/NYPLSAMLHelper.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogicUIDelegate.swift
Refactors the SAML code to remove a method that was duplicated identically in 2 classes. The refactored code was moved to NYPLSAMLHelper as-is. 
Changes in business logic are 99% just documentation + reorg.
This is part of https://jira.nypl.org/browse/SIMPLY-2510
Sign in via SAML using Columbia University test library. Ask for credentials if you don't have them.
n/a
yes
@ettore
> SIMPLY-2510 Move SAML sign-in logic out of VCs

- Simplified/ErrorHandling/NYPLAlertUtils.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLOPDSFeed.m
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/Network/NYPLRemoteViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
This does some preparation work for refactoring the duplicated logic present in NYPLAccountSignInViewController and NYPLSettingsAccountDetailViewController, by making it obvious which parts of the sign-in validation are indeed identical between the 2 classes. It is now simple to see that the following methods are almost identical:
- validateCredentials
- drmAuthorizeUserData:loggingContext:
- drmAuthorizeWithUsername:password:loggingContext:
- alertUserOfValidationError:problemDocData:response:loggingContext:
- authorizationAttemptDidFinish:error:errorMessage:
This enables a subsequent refactor to actually remove the duplication.
Unfortunately because the code was / is so messy, it might be difficult to see what changed in the Sign-in modal. I could not find another …
> SIMPLY-2510 Break up validation logic to highlight similarities between sign-in modal and account settings tab

- Simplified.xcodeproj/project.pbxproj
- Simplified/ErrorHandling/NYPLAlertUtils.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.h
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+UI.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- SimplifiedTests/NYPLSignInBusinessLogicTests.swift
Move logic that was in `authorizationAttemptDidFinish:error:errorMessage` (now renamed to `finalizeSignInForDRMAuthorization:error:errorMessage` to the business logic class since it is and should be identical between the 2 VCs. While doind this 2 changes were done:
1. the sign-in modal had 2 additional calls to `updateLoginLogoutCellAppearance` and `accountDidChange` that were actually redundant (i.e. already called)
2. the settings account VC did not have a call to `NYPLUserAccount::removeAll` in case of DRM failure, so this was added (it can't hurt, and there's no reason why one VC should have and the other not)
Also, `NYPLSignInBusinessLogic::logOutOrWarn(using:)` was moved as-is to the UI extension. …
> SIMPLY-2510 Refactor sign-in finalization logic

- Simplified/NYPLAnnotations.swift
- Simplified/NYPLBookRegistry.h
- Simplified/NYPLReadiumBookmark.swift
- Simplified/Reader2/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- Simplified/Reader2/UI/NYPLReaderPositionsVC.swift
Add, delete and sync bookmarks from server for R2
Probably easier to review by single commit
[SIMPLY-2804](https://jira.nypl.org/projects/SIMPLY/issues/SIMPLY-2804)
Make sure `bookmark syncing` is turned on in account detail
Open any epub book and create a bookmark
Go to bookmark list, the bookmark should be shown
Pull down to refresh and look for `server bookmark count` in debug area, which should be the same as the number of bookmarks in the list
*Since the bookmarks in the list could be local cache, this is the way to test the syncing without clearing the cache*
Delete a bookmark and repeat the step above to make sure bookmark on server is …
> SIMPLY-2804 R2 Bookmark syncing

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+DRM.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+UI.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogicUIDelegate.swift
Note that the 2 objc implementations of `drmAuthorizeWithUsername:password:loggingContext:` where slightly different in the 2 VCs, with the modal implementation performing an additional check to warn the user if the DRM authorization takes too long. Since this seems like a good idea, this is now added to both (the VC dismissal will result in nothing for a non-modal VC in the stack).
The implementations of `drmAuthorizeUserData:loggingContext` were instead identical in the 2 VCs.
Both are now rewritten in swift and added to NYPLSignInBusinessLogic as an extension.
https://jira.nypl.org/browse/SIMPLY-2510
As other PRs for this ticket, no …
> SIMPLY-2510 Refactor sign-in logic handling DRM authorization

- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
If we already added the "Signing Out" "linear view", we were skipping adding the view to the superview but at the same time we were still adding constraints to the newly created view in relation to the superview, which was nil, causing the crash.
This change makes the `setActivityTitleWithText` idempotent.
https://jira.nypl.org/browse/SIMPLY-3211
Steps are in the ticket description.
n/a/
yes
@ettore
> SIMPLY-3211 Don't add constraints for "Signing Out" view if already present

- Simplified.xcodeproj/project.pbxproj
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+CardCreation.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+DRM.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogicUIDelegate.swift
- Simplified/SignInLogic/NYPLUserAccountFrontEndValidation.swift
Removes the last part of sign-in business logic from the VCs:
- card creation logic
- DRM check in modal VC that automatically sign you in 
- implicit load of authentication document in settings account VC
Note that sign-out business logic is still in NYPLSettingsAccountDetailViewController.
https://jira.nypl.org/browse/SIMPLY-2510
test all ways of signing in and signing up in both the modal sign in page and the settings tab.
n/a
y
@ettore
> SIMPLY-2510 Refactor remaining sign-in business logic out of VCs

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- SimplifiedTests/Date+NYPLAdditionsTests.swift
- SimplifiedTests/Mocks/NYPLBookRegistryMock.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
Add unit tests and related mock models
Fix build error after pulling latest changes
Remove unnecessary background worker
Update bookmark UI on location changes
[SIMPLY-2804](https://jira.nypl.org/browse/SIMPLY-2804?filter=-1)
Run tests `NYPLReaderBookmarksBusinessLogicTests`
N/A
N/A
@ErnestFan
> SIMPLY-2804 Add unit tests for R2 bookmark business logic

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NYPLConfiguration+OE.swift
- Simplified/AppInfrastructure/NYPLConfiguration+SE.swift
- Simplified/AppInfrastructure/NYPLConfiguration.h
- Simplified/AppInfrastructure/NYPLConfiguration.m
- Simplified/AppInfrastructure/SimplyE-Bridging-Header.h
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/Settings/BarcodeScanning/NYPLBarcodeScanningViewController.h
- Simplified/Settings/NYPLSettingsPrimaryTableItem.swift
- Simplified/Settings/NYPLSettingsPrimaryTableViewController.swift
- Simplified/Settings/NYPLSettingsSplitViewController.swift
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/WelcomeScreen/NYPLWelcomeEULAViewController.swift
Removes the ZXing library and related client code from Open eBooks binary. 
It also enables opening links in the EULA welcome screen. Links are opened in Safari in order to continue to display the EULA in OE.
We cannot include and/or link to ZXing because that library accesses the camera, and that requires the NSCameraUsageDescription key in the app's info.plist. However, OE does not even use the camera.
The app settings tab should still be working as before.
n/a
yes
**Did someone actually run this code to verify it …
> Fix OE AppStore submission error and enables links in welcome EULA screen

- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLDeveloperSettingsTableViewController.swift
- Simplified/Settings/NYPLSettings.swift
Adds a switch in the Developer/testing menu to enable / disable R2.
https://jira.nypl.org/browse/SIMPLY-3102
Go to settings > developer menu and toggle the switch accordingly. Then open a book and verify it's being opened in R2 or R1. 
Closing and reopening the developer menu should persist the choice that was made.
none
yes
@ettore
> SIMPLY-3102 Add R2 toggle in developer menu

- Simplified.xcodeproj/project.pbxproj
- Simplified/Accounts/Library/Account.swift
- Simplified/AppInfrastructure/NYPLAppDelegate.m
- Simplified/Catalog/NYPLCatalogFeedViewController.m
- Simplified/Catalog/NYPLCatalogNavigationController.m
- Simplified/ErrorHandling/NYPLProblemDocument.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/MyBooks/NYPLMyBooksViewController.m
- Simplified/NYPLBookCellDelegate.m
- Simplified/NYPLBookRegistry.h
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLErrorLogger.swift
- Simplified/NYPLHoldsViewController.m
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Network/NYPLRemoteViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.h
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLReauthenticator.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/URLResponse+NYPLAuthentication.swift
- Simplified/Utilities/URLResponse+NYPL.swift
- Simplified/WelcomeScreen/OETutorialChoiceViewController.swift
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
Centralizes the logic to determine if an api call indicates that the authentication credentials have somehow expired for a currently signed-in user. Typically this can happen for Clever (and I think SAML) which is common in OE. In that case, the app will prompt the user to re-authenticate. I have not observed this happening ever for basic (barcode) authentication flows, although this should be able to handle that too.
The logic in question is `URLResponse+NYPLAuthentication.swift`. @leonardr I'd really appreciate it if you can take a look at that file and let me know if it makes sense to you, or if it's too generic. The idea is that we should be able to use it for any api call in SimplyE/OE (except card creator stuff I suppose).
**Why are we doing this? (w/ JIRA link …
> SIMPLY-3292 Re-authenticate if authentication expired

- OpenEbooks/OpenEBooks_OPDS2_Catalog_Feed-QA.json
- Simplified.xcodeproj/project.pbxproj
- Simplified/Accounts/Library/AccountsManager.swift
- Simplified/AppInfrastructure/NYPLConfiguration+OE.swift
- Simplified/Migrations/OEMigrations.swift
- Simplified/NYPLDeveloperSettingsTableViewController.swift
- Simplified/Settings/NYPLSettings+OE.swift
- Simplified/WelcomeScreen/OETutorialChoiceViewController.swift
- Adds QA library support to Open eBooks
- fixes a possible crash in OE.
https://jira.nypl.org/browse/SIMPLY-3292
This is necessary to test SIMPLY-3292 easily
Go to developer/testing menu to enable QA library, same as SimplyE
n/a
y
@ettore
> SIMPLY-3292 Add QA library support to OE

- Cartfile
- Cartfile.resolved
- Simplified/NYPLSettingsAccountDetailViewController.m
- Simplified/Settings/BarcodeScanning/NYPLBarcodeScanningViewController.m
- Simplified/software-licenses.html
Uses scanning view that matches the actual red rectangle displayed to the user.
Removes useless cruft.
https://jira.nypl.org/browse/SIMPLY-3161
Sign out and open barcode scanner from Settings > NYPL.
Center barcode in red box.
Profit (hopefully)
n/a
yes
@ettore
> SIMPLY-3161 Fix library card barcode scanning

- OpenEbooks/exportOptions-adhoc.plist
- OpenEbooks/exportOptions-appstore.plist
- Simplified.xcodeproj/project.pbxproj
- scripts/adobe-rmsdk-build.sh
- scripts/archive-and-upload-adhoc.sh
- scripts/build-3rd-parties-dependencies.sh
- scripts/xcode-export-adhoc.sh
- scripts/xcode-settings.sh
- Fixes some loose ends on the script to build Open Ebooks
- In the main script to build all 3rd parties dependencies, adds an option to skip building Adobe and R1 headers, since those almost never change.
CI
as usual, run these scripts from the root of the repo.
n/a
yes
@ettore
> Fix OE build from script and add option to skip building Adobe SDK dependencies

- Simplified/ErrorHandling/NYPLProblemDocumentCacheManager.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLBookDetailViewController.m
Complete the implementation of NYPLProblemDocumentCacheManager (Clear cache, get cached document etc)
[SIMPLY-3375](https://jira.nypl.org/browse/SIMPLY-3375)
Force a download fail on two different books, they should both show a problem document in the "View Issue" section
A download success on a book should remove the "View Issue" section
N/A
N/A
@ErnestFan
> [SIMPLY-3375] Fix NYPLProblemDocumentCacheManager

- Simplified/NYPLBookDetailDownloadFailedView.h
- Simplified/NYPLBookDetailDownloadFailedView.m
- Simplified/NYPLBookDetailView.m
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
"View Issues" section doesn't appear because there is no problem document when download failed.
The only fix for now is to remove the "Scroll down to view issue" message.
[SIMPLY-2961](https://jira.nypl.org/browse/SIMPLY-2961)
Force a download fail
The error message should be one line "The download could not be completed"
N/A
N/A
@ErnestFan
> SIMPLY-2961 "View Issues" section on Book Detail pages doesn't appear

- Simplified.xcodeproj/project.pbxproj
- Simplified/MyBooks/NYPLBook+DistributorChecks.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/NYPLBookCellDelegate.m
- scripts/build-3rd-party-dependencies.sh
- scripts/build-carthage.sh
- scripts/setup-repo-nodrm.sh
This fixes the build without DRM by excluding the private framework for processing Overdrive audiobooks.
The app should build without DRM / private repos.
Follow steps in README.
n/a
yes
@ettore
> Exclude Overdrive dependency from nondrm build

- .github/workflows/non-drm-build.yml
- .github/workflows/unit-testing.yml
- Simplified.xcodeproj/project.pbxproj
- scripts/archive-and-upload-adhoc.sh
- scripts/build-3rd-party-dependencies.sh
- scripts/decode-install-secrets.sh
- scripts/firebase/nypl-upload-symbols.sh
- scripts/ios-binaries-upload.sh
- scripts/setup-repo-drm.sh
- scripts/update-certificates.sh
- scripts/xcode-archive.sh
- scripts/xcode-build-nodrm.sh
- scripts/xcode-export-adhoc.sh
- scripts/xcode-settings.sh
- scripts/xcode-test.sh
Verifies that a new PR doesn't brake the non-DRM build.
This also contains some prep work for the bigger action to upload builds to iOS-binaries plus a minor refactor of the scripts. I left it here because I sort of developed those first before switching to the non-DRM build. Since it's foundation work I figure it's ok. This work is also divided in separate commits.
Since Simplified-iOS is a public repo that requires private dependencies to build with DRM support, we want to be good citizens and continue to support a version of the app without DRM support, using only publicly available code.
https://jira.nypl.org/browse/SIMPLY-3361
This will …
> SIMPLY-3361 Check nonDRM build on new PRs

- .github/workflows/unit-testing.yml
- .gitignore
- scripts/build-3rd-party-dependencies.sh
- scripts/build-carthage.sh
Changes the way we build the carthage dependencies so that they use the same command (`carthage bootstrap`) that we use on CI.
We should strive to have the local and CI builds match as much as possible.
CI should do this for us :)
n/a
n/a
**Did you bump the SimplyE build number?**
no code changes, so not needed
@ettore
> Get build scripts closer to CI build

- .github/workflows/archive-and-upload.yml
- .github/workflows/check-build-number.yml
- README.md
- scripts/ios-binaries-check.sh
Avoids checking out the entire iOS-binaries repo to just check the build number, and enables CI on feature branches.
better CI
n/a
n/a
yes
**Did you bump the SimplyE build number?**
n/a
@ettore
> Improve check build # workflow and enable Feature branches CI

- .github/workflows/archive-and-upload.yml
- .github/workflows/check-build-number.yml
- Simplified.xcodeproj/project.pbxproj
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- scripts/firebase-upload-symbols.sh
- scripts/firebase-upload.sh
Uploads build and dSYMs to Firebase. 
Note that the build is not automatically sent to testers because we need to add release notes first. 
The 2nd commit is unrelated but fixes a oversight bug introduced long time ago.
https://jira.nypl.org/browse/SIMPLY-3462
If the we are pushing to a release branch, we will upload to Firebase the App Store export instead of the adhoc. Otherwise, when pushing to develop or feature branch, we will upload the ad-hoc.
no and no
no
**Has the application documentation been updated for …
> SIMPLY-3462 Upload build to firebase

- Simplified/Reader2/Internal/DRMLibraryService.swift
- Simplified/Reader2/Internal/R2+NYPLAdditions.swift
- Simplified/Reader2/LCP/LCPLibraryService.swift
- Simplified/Reader2/NYPLR2Owner.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
Some methods are now deprecated in R2, so this fixes those. 
In particular the `downloadTask` in DRMFulfilledPublication seemed unused so I removed, but let me know if that's not ok.
trying to stay warning free.
n/a
n/a
no
yes
@ettore
> Fix usage of R2 deprecated methods

- Simplified.xcodeproj/project.pbxproj
Disables the ALWAYS_SEARCH_USER_PATHS build settings, which is deprecated since Xcode 8.3. 
Also sets up project for next release since we just code-froze 3.6.3. 
We want to distinguish builds on release branch (3.6.3) from the next release builds on develop.
n/a
n/a
not needed
n/a
@ettore
> Disable deprecated build setting and prepare for next version

- scripts/firebase-upload.sh
Fixes a CI error where the app-store exported build was uploaded to firebase, which is a problem because app-store builds are not directly installable. Ad-hoc should be used instead.
without this release builds on firebase are useless.
trigger CI on a release branch
n/a
no
yes
@ettore
> Always upload ad-hoc builds to firebase

- Simplified/Reader2/Internal/LibraryError.swift
- Simplified/Reader2/NYPLR2Owner.swift
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
Fixes a couple CP R2 localization strings and removed the ones related to the LCP passphrase screen which we no longer have.
https://jira.nypl.org/browse/SIMPLY-3429
When there's an error in the R2 reader, these strings will be presented for invalid books, open failures, unsupported format, corrupted book, DRM errors.
n/a
not really-- these changes are trivial, and we can wait for the next build
n/a
**Did someone actually run this code to verify it …
> SIMPLY-3429 Fix a few R2 strings and remove obsolete ones

- Cartfile
In order to get the fixes for race conditions when restoring the reading progress in [our fork of r2-navigator-swift](https://github.com/NYPL-Simplified/r2-navigator-swift), we will need to bring its `develop` branch up-to-date with upstream. However, that will break the current SimplyE build. To address this, I pushed a new [`develop-before-CP`](https://github.com/NYPL-Simplified/r2-navigator-swift/tree/develop-before-CP) branch on our fork that matches the same commit we currently use (`51a8dc1154fad6ad206bda00c8f3c4002cbada0d`). This way we can refer to that in the Cartfile (instead of `develop`) on the current SimplyE `develop` builds.
There are effectively no changes in build behavior for SimplyE on …
> Change branch reference for r2-navigator

- README.md
- scripts/build-carthage-R2-integration.sh
This is fixing the build with the R2dev target.
I recently broke the local build of R2 for development. 
n/a
need to do this before merging CP to develop
not needed
yes
@ettore
> Fix R2dev build and update README

- .github/workflows/check-build-number.yml
- Simplified/AppInfrastructure/NSNotification+NYPL.swift
- Simplified/NYPLBookButtonsView.h
- Simplified/NYPLBookButtonsView.m
- Simplified/NYPLBookDetailButtonsView.m
- Simplified/NYPLBookRegistry.m
- Simplified/NYPLOPDSAcquisitionAvailability.h
Shows a spinning indicator in My Books or other book table view cells when the user taps on the Read button. This provides a visual indicator for the delay caused by syncing the reading position and opening R2.
While working on this I saw that NYPLBookButtonsView and NYPLBookDetailButtonsView share 90% of the code. I plan to refactor these in SIMPLY-3621 but here I highlighted the differences to make that more obvious.
https://jira.nypl.org/browse/SIMPLY-3618
(https://jira.nypl.org/browse/SIMPLY-3621)
I will add steps in the ticket.
n/a
**Does this include changes that require a new …
> SIMPLY-3618 Show spinner when tapping Read button

- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/xcshareddata/xcschemes/Open eBooks.xcscheme
- Simplified.xcodeproj/xcshareddata/xcschemes/SimplyE.xcscheme
Fixes crashes on iOS 14.5 beta when generating cover from book with non ASCII characters
https://jira.nypl.org/browse/SIMPLY-3578
The original crash was found on iOS devices running iOS 14.5 beta while displaying books with no covers that have accented letters in their title (https://cdncms.fonts.net/images/de7722aa7a6beee0/D.Accents.jpg). To test the fix, try viewing such books in the list on a device running iOS 14.5 beta. The app should not crash while viewing those books.
n/a
Yes
**Has the application documentation …
> SIMPLY-3578: Fixed crashes on iOS 14.5 beta when generating cover from book with non ASCII characters

- Simplified/NYPLBookDetailViewController.m
- Simplified/Network/NYPLCaching.swift
- Simplified/Network/NYPLNetworkExecutor.swift
Uses Network Executor for reporting errors with a book
https://jira.nypl.org/browse/SIMPLY-3511
n/a
No
n/a
> SIMPLY-3511: Use Network Executor for reporting errors with a book

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/Bookmarks/NYPLAnnotations+Deprecated.swift
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Reader2/Bookmarks/NYPLBookmarkFactory.swift
- Simplified/Reader2/Bookmarks/NYPLReadiumBookmark.swift
- Simplified/Reader2/BusinessLogic/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkDecodingTests.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkSpecTests.swift
Adds unit tests for deserializing bookmarks in the new Spec format. 
Also adds the necessary changes in the bookmarks parsing/creation code. Since these are breaking changes with R1, I'm merging this in a feature branch until this refactor is complete.
https://jira.nypl.org/browse/SIMPLY-3655
too early to test. This is just a subtask.
no -- merging into feature branch
not yet
yes
@ettore
> SIMPLY-3655 New bookmark format deserialization

- Simplified.xcodeproj/project.pbxproj
- Simplified/Book/Models/NYPLBookRegistry.h
- Simplified/Reader2/Bookmarks/NYPLBookmarkFactory.swift
- Simplified/Reader2/Bookmarks/NYPLReadiumBookmark.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkDecodingTests.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkSpecTests.swift
- SimplifiedTests/Bookmarks/NYPLR1BookmarkDecodingTests.swift
- SimplifiedTests/Bookmarks/only-essential-info-bookmark.json
- SimplifiedTests/Bookmarks/valid-R1-bookmark-1.json
- SimplifiedTests/Bookmarks/valid-R1-readingprogress-1.json
Ensures that despite the changes for the new bookmarks spec we can still read R1 bookmarks in the old format.
https://jira.nypl.org/browse/SIMPLY-3669
not ready for QA, will be when the story is completed
I'll need to update the commit reference for the Simplified-Bookmark-Spec repo once the PR https://github.com/NYPL-Simplified/Simplified-Bookmarks-Spec/pull/3 is merged.
not yet
y
@ettore
> SIMPLY-3669 Ensure ability to read R1 bookmarks

- Simplified.xcodeproj/project.pbxproj
- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/NYPLReaderReadiumView.m
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Reader2/Bookmarks/NYPLBookLocation+Locator.swift
- Simplified/Reader2/Bookmarks/NYPLBookmarkFactory.swift
- Simplified/Reader2/Bookmarks/NYPLBookmarkSpec.swift
- Simplified/Reader2/Bookmarks/NYPLReadiumBookmark+R2.swift
- Simplified/Reader2/Bookmarks/NYPLReadiumBookmark.swift
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionPoster.swift
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionSynchronizer.swift
- Simplified/Reader2/BusinessLogic/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/Internal/Publication+NYPLAdditions.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkDeserializationTests.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkSerializationTests.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkSpecTests.swift
- SimplifiedTests/Bookmarks/NYPLR1BookmarkDeserializationTests.swift
- SimplifiedTests/Mocks/NYPLBookRegistryMock.swift
- SimplifiedTests/NYPLFake.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
Enforces creation of new bookmarks following the spec. This now includes:
- when creating a bookmark in a ereader context, we use the R2 Publication object to derive the `href` upfront and store it in the bookmark, instead of doing it later. 
- when creating a bookmark from the dictionary representation, the `href` may be nil if the bookmark was created in R1. In this case the `href` can be derived only when we open the book. However in this case the `idref` MUST be not nil. This is now expressed at compile time via the `ChapterID` enum.
- when creating a dictionary representation, always save all fields required by the spec, and not old ones
- mark the total progression as non-optional, per bookmark spec. …
> SIMPLY-3670 Reconciliate old bookmark format with new format

- Simplified.xcodeproj/project.pbxproj
- Simplified/AxisService/NYPLAxisDRMAuthorizer.swift
- Simplified/Book/Models/NYPLBook.m
- Simplified/Migrations/OEMigrations.swift
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+Adept.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+Axis.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+DRM.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
Removes Adept and LCP from OpenEbooks and Makes Axis360 preferred acquisition for downloading books.
With this, we no longer need any hacks to present a custom feed to the user for testing Axis content download.
https://jira.nypl.org/browse/SIMPLY-3607
Can not be QA tested by itself. For devs, when downloading a book on OpenEbooks, a link with Axis DRM will be preferred over any other link.
N/A
N/A
N/A
**Did someone actually run this code to verify …
> SIMPLY-3607: Removes Adept and LCP from OpenEbooks

- Simplified/AppInfrastructure/NYPLConfiguration+OE.swift
Fixes user unable to sign in with beta libraries. Requires https://github.com/NYPL-Simplified/Simplified-iOS/pull/1360 to be merged in order to work.
https://jira.nypl.org/browse/SIMPLY-3671
Follow the steps to reproduce in the ticket
This will only work after https://github.com/NYPL-Simplified/Simplified-iOS/pull/1360 has been merged.
N/A
N/A
> SIMPLY-3671: Fixed user unable to sign in using beta libraries

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Reader2/Bookmarks/NYPLBookmarkFactory.swift
- SimplifiedTests/Bookmarks/NYPLAnnotationResponseTests.swift
- SimplifiedTests/Bookmarks/NYPLBookmarkSpecTests.swift
- SimplifiedTests/Bookmarks/annotation-response.json
The `syncReadingPosition` and `getServerBookmarks` functions call the same api, so the parsing of the api response is identical. This PR moves the parsing code into its own function, so it can be reused by the two api call wrappers. Also adds related unit tests.
Minor: in NYPLAnnotations, `postAnnotation` and `annotationID(fromNetworkData:)` have been moved as-is.
https://jira.nypl.org/browse/SIMPLY-3668
will be able to test once all story subtasks have been completed. 
merging to feature branch
not needed
**Has the …
> SIMPLY-3668 Refactor GET annotations api calls

- Simplified/AxisService/NYPLAxisDRMAuthorizer.swift
- Simplified/AxisService/NYPLAxisService.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Gets DeviceID and Client IP for AXIS license URL generation 
We need deviceID and clientIP in order to generate a url for downloading the license file for AXIS books.
https://jira.nypl.org/browse/SIMPLY-3672
Too early to test
N/A
N/A
N/A
> SIMPLY-3672: Get DeviceID and Client IP for AXIS license URL generation 

- Simplified/AxisService/NYPLAxisService.swift
- Simplified/Book/Models/NYPLBookContentType.h
- Simplified/Book/Models/NYPLBookContentType.m
- Simplified/Book/UI/NYPLBookButtonsView.m
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Moves downloaded book content from downloads to content directory.
https://jira.nypl.org/browse/OE-16
Too early to test.
N/A
N/A
N/A
Raman Singh verified it.
> OE-16: Move downloaded content for AXIS books to books directory

- Simplified.xcodeproj/project.pbxproj
- Simplified/AxisService/NYPLAssetWriter.swift
- Simplified/AxisService/NYPLAxisKeysProvider.swift
- Simplified/AxisService/NYPLAxisLicenseURLGenerator.swift
- Simplified/AxisService/NYPLAxisPackageEndpointProvider.swift
- Simplified/AxisService/NYPLAxisPackagePathPrefixProvider.swift
- Simplified/AxisService/NYPLAxisService.swift
- Simplified/AxisService/NYPLAxisXML.swift
- Simplified/AxisService/NYPLRSACypher.swift
- Simplified/Logging/NYPLErrorLogger.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Downloads required files for books with AXIS DRM
https://jira.nypl.org/browse/OE-19
User should be able to download an AXIS book using QA library
Relies on https://github.com/NYPL-Simplified/Simplified-iOS/pull/1367 to be merged in in order to avoid crashing upon book download
N/A
N/A
Raman Singh verified it.
> OE-19: Download required files for books with AXIS DRM

- Simplified.xcodeproj/project.pbxproj
This simply updates the reference commit for the TenPrintCoverView library to include the fix @singhraman4282 did some time ago for SimplyE. This crash occurs also on Open eBooks but it's not as severe because we verified all books currently have covers. However, a failure can always happens and in that the app will crash on iOS 14.5.
https://jira.nypl.org/browse/OE-75
I will add QA steps in the ticket
This is a hot fix that should be released ASAP, it's merging on the old 1.9.0 release baseline.
definitely. 
**Has the …
> OE-75 Hotfix to fix TenPrintCoverView crash on iOS 14.5

- Simplified.xcodeproj/project.pbxproj
While updating the build to Xcode 12 I missed to embed the frameworks for OE. It was not caught by CI because we don't build OE for release in our CI. This set up now mimics SimplyE, except for the ZXing framework which is not needed on OE.
to fix the Open eBooks build
no QA, should be able to build and run the app.
n/a
n/a since there's no OE CI.
n/a
@ettore
> IOS-117 Add OE frameworks to Embed build phase

- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/xcshareddata/xcschemes/SimplyE-R2dev.xcscheme
- SimplifiedR2.xcworkspace/contents.xcworkspacedata
- scripts/build-carthage-R2-integration.sh
- scripts/build-carthage.sh
- scripts/clean-carthage.sh
- fixes the R2dev target that we use when working on R2 upgrades, adapting to Xcode 12
- somehow Xcode cannot reliably detect the build order of all the frameworks in the SimplifiedR2 workspace, so I disabled the "Parallelize builds" option, and added R2Shared as the first target to be built. This seems to push Xcode in the right direction. Otherwise, you'd have to build the target twice (literally: the first failed with "R2Shared unavailable" but still went ahead and built it after (e.g.) ReadiumLCP, so the 2nd build would then succeed).
- I removed the CardCreator target because it seems like we rarely use it and maintaining that too has a high cost. Please let me know if you disagree and why, I can restore it. …
> IOS-118 Fix target for R2 development/integration, remove card creator target

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMContentProtection.swift
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMFetcher.swift
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/NYPLAdobeContentProtectionService.swift
- Simplified/Reader2/ReaderStackConfiguration/LibraryService.swift
This is addressing the breakage we experienced after upgrading the latest R2 version, `2.0.0-beta.2`, after which opening books with Adobe DRM started failing. The [issue](https://github.com/readium/r2-shared-swift/issues/136) I opened on r2-shared-swift adds more background. This commit follows some of the suggestions from @mickael-menu from that discussion, particularly the requirement to have a `ContentProtectionService` implementation and making sure to close the `fetcher` once done. 
I decided for now to stick with our current fetcher implementation because it has been QA'ed for a while now and so far it has been reliable. The other solutions (such as using `TransformingFetcher` instead of our own custom implementation) are probably more correct but it seems risky …
> IOS-193 Fix AdobeDRM decoding after recent changes in R2Shared

- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
If Adobe DRM fails fulfilling a book loan request for whatever reason, SimplyE silently swallows the error and proceeds as nothing happened. This changes the behavior to fail immediately and report an error to the user.
https://jira.nypl.org/browse/IOS-199
We should verify fulfillment works as before in the and that there are not false positives reported by Adobe. A regression should cover this.
Requires https://github.com/NYPL-Simplified/DRM-iOS-Adobe/pull/20 to be merged first, then I have to update the commit hash for this PR to match that.
**Does this include changes that require a …
> IOS-199 Error out if Adobe fulfillment fails

- Simplified.xcodeproj/project.pbxproj
- Simplified/Accounts/Library/AccountsManager.swift
- Simplified/AppInfrastructure/NYPLConfiguration+OE.swift
- Simplified/AppInfrastructure/NYPLConfiguration+SE.swift
- Simplified/LibraryFinder/NYPLLibraryFinderBusinessLogic.swift
- Simplified/LibraryFinder/UI/NYPLLibraryFinderLibraryCell.swift
- Simplified/LibraryFinder/UI/NYPLLibraryFinderViewController.swift
- Simplified/Settings/NYPLSettingsAccountsList.swift
- Simplified/WelcomeScreen/NYPLWelcomeScreenViewController.swift
- SimplifiedTests/Mocks/NYPLLibraryRegistryFeedRequestHandlerMock.swift
- SimplifiedTests/NYPLFinderBusinessLogicTests.swift
Dependency inject `AccountsManager` into `NYPLFinderBusinessLogic` in order to load registry feed
Construct request URL with new endpoints, user's location and search keyword
Some minor UI fixes and clean up
[iOS-37](https://jira.nypl.org/browse/IOS-37)
Not ready to be tested
N/A
N/A
N/A
@ErnestFan
> iOS-37 Call new endpoints for LibraryRegistry

- OpenEbooks/OpenEBooks_OPDS2_Library_Registry_Feed-QA.json
- OpenEbooks/OpenEBooks_OPDS2_Library_Registry_Feed.json
- Simplified.xcodeproj/project.pbxproj
Update the format of OpenEbooks library registry feed to match the new OPDS2 parser
[iOS-202](https://jira.nypl.org/browse/IOS-202)
Launch OpenEbooks
Login
Library and publications should load without issue
N/A
N/A
N/A
@ErnestFan
> iOS-202 Update OpenEbooks OPDS2 library registry feed

- Simplified/Reader2/ReaderPresentation/ReaderModule.swift
Dismisses book details view controller if presented before opening the book
https://jira.nypl.org/browse/OE-133
Follow the steps in the ticket
N/A
Not yet
N/A
Raman Singh verified on iPhone 12 Pro Max (14.4), iPad 9.7 inch Pro (13.3), and iPad 12.9 inch Pro (14.4)
> OE-133: Opening a book from book details page dismisses book details page

- Simplified/Reader2/ReaderPresentation/NYPLRootTabBarController+R2.swift
Hide activity indicator in book details view controller when book processing is completed
https://jira.nypl.org/browse/OE-137
Follow the steps in the ticket
N/A
Not yet
N/A
Raman Singh verified on iPhone 12 pro max (14.2) and iPad 9 Pro (13.7)
> OE-137: Hide activity indicator when book processing is completed

- Simplified.xcodeproj/project.pbxproj
Removes some duplicated entries in the Compile Source build phase that were producing warnings on the Axis feature branch.
We Shall Have No Compile Warnings
just a build issue, nothing to QA
n/a
no
n/a
@ettore built all targets except the R2-dev target.
> Fix warnings about duplicated compilation

- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- SimplifiedTests/NYPLMyBooksDownloadCenterTests.swift
Removes a very misleading log line and slightly improves readability in code detecting supported acquisition types.
The removed log line caused confusion while QA'ing IOS-205.
nothing to check per se that is not covered by a regression.
n/a
no
y
@ettore
> Remove misleading log line + improve readability

- README.md
- Simplified.xcodeproj/project.pbxproj
- scripts/build-carthage.sh
- scripts/buildNYPLAxis.sh
- scripts/setup-repo-drm.sh
- Updates the README removing references of Adobe
- Moves axis repo checkout to setup script
- Removes Axis build script since Xcode automatically builds linked subproject targets
regular maintenance / Ettore getting comfortable with new Axis code
n/a
merging to feature branch
no
yes
@ettore
> Streamline Axis build and update README

- Simplified.xcodeproj/project.pbxproj
- pull_request_template.md
This should trigger and deliver a build of Open eBooks to Firebase.
https://jira.nypl.org/browse/OE-157
This should receive a regression test to verify R2 works correctly on Open ebooks too.
n/a
**Does this include changes that require a new SimplyE or Open eBooks build for QA?**
yes
n/a
@ettore
> Bump OE version number to 2.0.0 and update PR template

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/BusinessLogic/NYPLR1R2UserSettings.swift
- Simplified/Reader2/BusinessLogic/NYPLReaderSettings+Conversions.swift
- Simplified/Reader2/UI/NYPLReaderSettingsView.h
- Simplified/Reader2/UI/NYPLReaderSettingsView.m
- Simplified/Reader2/UI/NYPLUserSettingsVC.swift
- SimplifiedTests/NYPLReaderSettingsTests.swift
- scripts/build-carthage-R2-integration.sh
- scripts/checkout-r2-branch.sh
- adds toggle for disabling publisher's epub defaults
- minor refactor of our user settings
- adds a script to easily toggle between the stable tags and the `develop` branch of the R2 repos 
https://jira.nypl.org/browse/IOS-234
see ticket
this will appear in the next SimplyE
yes
yes
@ettore
> IOS-234 Add Publisher's defaults toggle

- Simplified/Reader2/UI/NYPLReaderSettingsView.m
Simply hides the row with the toggle but leaves the view installed so that the existing layout code doesn't need to be changed drastically. 
https://jira.nypl.org/browse/OE-178
see ticket
merging to develop since just to be on the safe side, and since this is unrelated to Axis DRM.
no, because I will merge develop into the feature branch and then build Axis branch instead.
n/a …
> OE-178 Hide Publisher's defaults toggle till UX approval

- Simplified.xcodeproj/project.pbxproj
- Simplified/software-licenses.html
fixes up the software license file since we don't have Adobe anymore
legal reasons 
open software licenses item in Settings
merging to feature branch
no
n/a
@ettore
> Remove adobe from OE license

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NYPLBookContentMetadataFilesHelper.swift
- Simplified/Book/Models/NYPLBookRegistry.h
- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/Migrations/OEMigrations.swift
Emergency brute force fix that removes all downloads and updates the book registry to say that the currently loaned books need to be re-downloaded. This is for fixing the inability to read previously downloaded Adobe DRM content. 
https://jira.nypl.org/browse/OE-181
- Install OE 2.0.0 (3) from Firebase and download a book. This will be in Adobe format.
- Install OE 2.1.0 (5) from Firebase. The adobe book should still appear in My Books but you won't be able to open that book anymore. Download an additional book.
- install OE 2.1.1 from Firebase or TestFlight. You should still be able to see both books in My Books, but those books will need to …
> IOS-181 Remove OE downloaded content hot-fix

- Simplified/Logging/NYPLErrorLogger.swift
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
Adds the errors received when POSTing annotations to the Crashlytics report. 
https://jira.nypl.org/browse/IOS-263
no changes in  behavior should be experienced by the user. The part of the regression that covers reading progress updates and bookmarks should cover this.
n/a
no -- however after this I will start a new release for SimplyE.
yes
@ettore
> IOS-263 Log annotation api errors to Crashlytics

- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Adds a nil check to fix a crash and also add a log event to try to diagnose why the nil id is happening in the first place. See full analysis in ticket.
https://jira.nypl.org/browse/IOS-270
I don't have steps to reproduce this issue. I will try to add some details for QA in the ticket.
n/a
no
y
@ettore
> IOS-270 Fix + log more info for crash on book return

- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLUserAccountFrontEndValidation.swift
On the sign in UI (both in Settings tab and modal) this configures the Return button for the Username field to advance to the PIN field; the Return button for the PIN field to attempt to log in.
This also refactors the logic that determines when the Log In button is enabled, and reuses it for triggering login when the user presses the Done button on the PIN keyboard.
https://jira.nypl.org/browse/IOS-172
See ticket
n/a
no
n/a
**Did someone …
> IOS-172 Advance to PIN after hitting Return on Barcode field

- Cartfile.resolved
- Simplified/AppInfrastructure/NYPLConfiguration+Color.swift
- Simplified/AppInfrastructure/NYPLRootTabBarController.m
- Simplified/Book/UI/NYPLBookButtonsView.m
- Simplified/Book/UI/NYPLBookDetailDownloadFailedView.m
- Simplified/Book/UI/NYPLBookDetailDownloadingView.m
- Simplified/Book/UI/NYPLBookDetailView.m
- Simplified/Book/UI/NYPLBookDetailsProblemDocumentViewController.swift
- Simplified/Book/UI/NYPLBookDownloadingCell.m
- Simplified/Catalog/NYPLContentTypeBadge.swift
- Simplified/Holds/NYPLHoldsViewController.m
- Simplified/Reader2/UI/NYPLReaderPositionsVC.swift
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/WelcomeScreen/OETutorialViewController.swift
Update git submodules for Dark Mode UI changes
Update UI on certain views when user switch to light/dark mode
[iOS-247](https://jira.nypl.org/browse/IOS-247)
Switch between light and dark mode when performing the action below and make sure the UI matches the one in [Figma](https://www.figma.com/file/SbU22GePd2pXUQ5yrauF15/Dark-Mode?node-id=208%3A37)
1. Open SE/OE
2. Borrow an audiobook and listen to it
3. Check the UI of book download and failure
4. Check the UI of CardCreator process
CardCreator-iOS, NYPLAEToolkit and NYPLAudiobookToolkit are updated but should not cause any issues …
> [iOS-247] Update colors and git submodules for Dark Mode

- .github/workflows/archive-and-upload.yml
- .github/workflows/non-drm-build.yml
- .github/workflows/unit-testing.yml
- .gitmodules
- Cartfile
- Cartfile.resolved
- RDServices.xcodeproj/project.pbxproj
- RDServices.xcodeproj/xcshareddata/xcschemes/RDServices.xcscheme
- README.md
- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/xcshareddata/xcschemes/Open eBooks.xcscheme
- Simplified.xcodeproj/xcshareddata/xcschemes/SimplyE-R2dev.xcscheme
- Simplified.xcodeproj/xcshareddata/xcschemes/SimplyE-noDRM.xcscheme
- Simplified.xcodeproj/xcshareddata/xcschemes/SimplyE.xcscheme
- Simplified/Accounts/AgeCheck/NYPLAgeCheck.swift
- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/Reader2/UI/NYPLReaderPositionsVC.swift
- Simplified/Reader2/UI/NYPLReaderSettingsView.swift
- scripts/bootstrap-drm.sh
- scripts/build-NYPLAEToolkit.sh
- scripts/build-carthage.sh
- scripts/build-dependencies.sh
- scripts/prepare-carthage.sh
- scripts/xcode-archive.sh
- scripts/xcode-build-nodrm.sh
- scripts/xcode-test.sh
- Moved CardCreator back to Carthage
- Moved build of NYPLAEToolkit to a manual build since it doesn't seem to work via Carthage on CI because of permissions
Leaving both libraries as Xcode subprojects inexplicably makes Xcode 13 complain about duplicated symbols.
https://jira.nypl.org/browse/IOS-264
if the build succeeds, the regression will cover the rest.
n/a
yes
yes
@ettore
> IOS-264 Update to Xcode 13

- Cartfile.resolved
- README.md
- scripts/build-carthage-R2-integration.sh
Pulls in changes for fixed warnings in NYPLAudiobookToolkit, makes the R2 integration script work without DRM support and updates the README accordingly.
IOS-264
n/a
n/a
no
yes
@ettore
> IOS-264 Update Cartfile, improve README + R2 integration script

- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Add info about book instance being nil or not in the context of diagnosing IOS-270
https://jira.nypl.org/browse/IOS-270
https://jira.nypl.org/browse/IOS-277
n/a
n/a
no
n/a
@ettore
> IOS-277 Add info about book being nil to log event

- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
While in Light mode, the Sync Bookmarks switch appeared with the blue color used for Dark Mode.
Also removed unneeded error report for a condition that is not an error.
https://jira.nypl.org/browse/IOS-299
will update ticket
n/a
no
n/a
@ettore
> IOS-299 Fix color issue in Light Mode and remove unneeded error report

- Simplified/Book/UI/NYPLBookCellDelegate+Audiobooks.m
adds book details to audiobook errors logged to Crashlytics
https://jira.nypl.org/browse/IOS-57
will add details in ticket
n/a
no
n/a
@ettore
> IOS-57 Add book info to audiobook error report

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionPoster.swift
- Simplified/Reader2/BusinessLogic/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- SimplifiedTests/Mocks/NYPLAnnotationsMock.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
Dependency inject NYPLAnnotations
Implement mocked NYPLAnnotations for unit testing
Update existing tests and add new test cases
[iOS-148](https://jira.nypl.org/browse/IOS-148)
N/A
N/A
N/A
N/A
@ErnestFan
> IOS-148 Dependency inject NYPLAnnotations and update unit tests

- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Reader2/Bookmarks/NYPLBookmarkFactory.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
Logs book information to log lines recorded before the crash described in IOS-316. Hopefully this can help us reproduce the crash by trying the same books where the crash happens.
I also added a commit to remove a log statement in relation to IOS-277, since we verified that things are good there. See IOS-277 for more details.
https://jira.nypl.org/browse/IOS-317
no QA necessary beside the regression.
n/a
no. These changes will be verified during regression.
**Has the application documentation been updated …
> IOS-317 Add book info logging to diagnose crash

- Simplified.xcodeproj/xcshareddata/xcschemes/Open eBooks.xcscheme
just updating the git submodule refs for unit testing and removing a module unit tests from the remaining scheme, since we now do testing for the submodules in their respective repos.
https://jira.nypl.org/browse/IOS-304
n/a since this is only  a behind the scenes change
n/a
no
yes
@ettore
> IOS-304 Update submodule refs for spm unit testing

- Simplified.xcodeproj/project.pbxproj
- Simplified/AxisService/Download/NYPLAxisDRMAuthorizer.swift
- Simplified/AxisService/Read/NYPLAxisBookReadingAdapter.swift
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMContentProtection.swift
- Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisProtectedAssetHandler.swift
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+Adept.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+Axis.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+DRM.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+SignOut.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+UI.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- SimplifiedTests/NYPLSignInBusinessLogicTests.swift
- compiles Adobe AND Axis for SimplyE
- fixes/hacks to abort Axis decryption if not present, and likewise prevent Adobe content decryption if Axis DRM is present.
https://jira.nypl.org/browse/IOS-332
will update ticket
I think we should do 2 things:
- first review the code and see if the hacks are safe and if there's a chance for them to cause side effects.
- if that checks out, let's merge it now so that a build can start.
- We should though fix the hacks right after, and merge them to develop in a separate PR
**Does this include changes that require a new SimplyE/Open eBooks build for …
> IOS-336 Add Axis support to SimplyE

- Simplified/AxisService/Read/NYPLAxisBookReadingAdapter.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMContainer.h
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMContainer.mm
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMContentProtection.swift
- Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMLibraryService.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+Adept.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+Axis.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+DRM.swift
Encapsulate content protection and sign-in process for each DRMs
[iOS-339](https://jira.nypl.org/browse/IOS-339)
[Banned Books PR](https://github.com/NYPL-Simplified/Simplified-iOS/pull/1532)
Regression testing for account sign-in and sign-out on SE and OE
Open and read publications protected by each DRMs or without DRM
N/A
Yes, will do before merge
No
@ErnestFan
> iOS-339 Fixes for hacks introduced by banned book feature

- .github/workflows/archive-and-upload.yml
- Simplified.xcodeproj/project.pbxproj
- Simplified/Settings/NYPLSettingsAccountsListVC.swift
- Prevents our CI to send a text message when it cannot authenticate with apple
- fixes a crash in the settings tab (separate commit).
https://jira.nypl.org/browse/IOS-338
once a build is triggered and the build succeeds, we should be good.
For the other commit, the regression will cover this.
n/a
yes
yes
@ettore
> IOS-338 Prevent 2FA on CI jobs and fix possible crash

- Simplified.xcodeproj/project.pbxproj
- Simplified/Logging/NYPLErrorLogger.swift
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
Use NYPLErrorLogger to log events in NYPLAnnotations
[ios-149](https://jira.nypl.org/browse/IOS-149)
[Previous PR on NYPLAnnotations](https://github.com/NYPL-Simplified/Simplified-iOS/pull/1232#discussion_r513035443)
No testing needed
N/A
N/A
N/A
N/A
> iOS-149 Use NYPLErrorLogger to log events in NYPLAnnotations

- .github/workflows/archive-and-upload.yml
- Gemfile
Print Fastlane version before upload
Fastlane version is buried in the CI log and hard to find
N/A
N/A
N/A
N/A
N/A
> Print Fastlane version before archive-and-upload

- Simplified/Accounts/AgeCheck/NYPLAgeCheck.swift
- Simplified/Accounts/Library/Account.swift
- Simplified/Accounts/User/NYPLUserAccount.swift
- Simplified/AppInfrastructure/NYPLAppDelegate+OE.swift
- Simplified/Book/UI/NYPLBookButtonsView.m
- Simplified/Book/UI/NYPLBookCellDelegate.m
- Simplified/Holds/NYPLHoldsViewController.m
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/MyBooks/NYPLMyBooksViewController.m
- Simplified/Network/NYPLRemoteViewController.m
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/Settings/NYPLSettingsSplitViewController+OE.swift
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLReauthenticator.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogicUIDelegate.swift
- Simplified/WelcomeScreen/OETutorialChoiceViewController.swift
- SimplifiedTests/Mocks/NYPLUserAccountProviderMock.swift
- SimplifiedTests/OPDS2CatalogsFeedTests.swift
- removes some unused authentication logic
- rename a few variables for clarity in authentication logic
This is some preparatory work for OE-216. It's the first of 3 PRs.
too early to test
This should be safe to merge, since it should have no changes in functionality.
no
yes
@ettore
> OE-216 Remove unused authentication logic

- Simplified/Book/UI/NYPLBookDetailViewController.m
- Simplified/Logging/NYPLCirculationAnalytics.swift
- Simplified/Logging/NYPLErrorLogger.swift
- Simplified/Migrations/OEMigrations.swift
- Simplified/Migrations/SEMigrations.swift
- Simplified/Network/NYPLCaching.swift
- Simplified/Network/NYPLNetworkExecutor.swift
- Simplified/Network/NYPLNetworkQueue.swift
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Network/NYPLRequestExecuting.swift
- Simplified/Network/NYPLSession.m
- Simplified/OPDS/NYPLOPDSFeedFetcher.swift
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionPoster.swift
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionSynchronizer.swift
- Simplified/Reader2/UI/NYPLReaderPositionsVC.swift
- Simplified/Settings/NYPLSettingsAdvancedViewController.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+BookmarkSyncing.swift
- SimplifiedTests/Bookmarks/NYPLAnnotationResponseTests.swift
- SimplifiedTests/Mocks/NYPLAnnotationsMock.swift
- SimplifiedTests/Mocks/NYPLOPDSFeedFetcherMock.swift
- SimplifiedTests/NYPLCatalogUngroupedFeedTests.swift
Routes all annotations calls to our centralized network layer so that they can take advantage of caching, bearer token refresh, etc.
https://jira.nypl.org/browse/IOS-335
I think a regression focused on bookmarks and reading position should cover this. There are no user-level changes.
required for 2.4.0 release.
not yet. There's another PR I will submit after this.
yes
@ettore
> IOS-335 Use network layer for annotations calls

- Simplified.xcodeproj/project.pbxproj
- Simplified/Audiobooks/AudiobookManifestAdapter.swift
- Simplified/Audiobooks/AudiobookManifestHelper.swift
- Simplified/Audiobooks/NYPLAudiobookDownloader.swift
- Simplified/Book/UI/NYPLBookCellCollectionViewController.m
- Simplified/Book/UI/NYPLBookCellDelegate+Audiobooks.m
- Simplified/Book/UI/NYPLBookCellDelegate.m
- Simplified/Book/UI/NYPLBookDownloadingCell.h
- Simplified/Book/UI/NYPLBookDownloadingCell.m
- Simplified/MyBooks/NYPLMyBooksDownloadCenter+AudiobooksDownload.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.h
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Refactor code to create audiobook object for background download process
Implement downloader to download audiobooks in queue
Implement download status protocol to interfere with MyBooksDownloadCenter
[iOS-390](https://jira.nypl.org/browse/IOS-390)
[iOS-391](https://jira.nypl.org/browse/IOS-391)
Will be tested once the UI ticket is done
NYPLAudiobookToolkit and NYPLAEToolkit have been updated
Not until UI is ready
N/A
**Did someone …
> iOS-390/391 Implement audiobook download in background

- Simplified.xcodeproj/project.pbxproj
- Simplified.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Simplified/Audiobooks/NYPLAudiobookDownloader.swift
- Simplified/Book/UI/NYPLBookCellDelegate+Audiobooks.m
- Simplified/Book/UI/NYPLBookDetailView.m
- Simplified/Book/UI/NYPLBookDetailViewController.m
- Simplified/Book/UI/NYPLBookDownloadingCell.m
- Simplified/Logging/NYPLErrorLogger.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter+AudiobooksDownload.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Log audiobook download timeout and slow download
Add audiobook to downloader before presenting audiobook in order to log download error
[iOS-393](https://jira.nypl.org/browse/IOS-393?focusedCommentId=70188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-70188)
See [iOS-389](https://jira.nypl.org/browse/IOS-389)
Updated dependencies
Will bump build number before merge
N/A
**Did someone actually run this code …
> iOS-393 Log audiobook download timeout and slow download

- Simplified.xcodeproj/project.pbxproj
- Simplified/Accounts/User/NYPLUserAccount.swift
- Simplified/AppInfrastructure/NYPLAppDelegate+OE.swift
- Simplified/AppInfrastructure/NYPLAppDelegate.m
- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/Catalog/NYPLCatalogNavigationController.m
- Simplified/Catalog/NYPLCatalogs+OE.swift
- Simplified/ErrorHandling/NYPLAlertUtils.swift
- Simplified/Holds/NYPLHoldsViewController.m
- Simplified/Keychain/NYPLKeychainStoredVariable.swift
- Simplified/MyBooks/NYPLMyBooksViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic+OAuth.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+UI.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/NYPLSignInCleverHelper.swift
- Simplified/SignInLogic/OELoginChoiceViewController.swift
- Simplified/SignInLogic/OELoginCleverHelper.swift
- Simplified/SignInLogic/OELoginFirstBookVC.swift
- Simplified/WelcomeScreen/OEEULAViewController.swift
Refactors Clever authentication logic for the new login harmonization flow. I left a checkin with the implementation of using SFSafariViewController and ASWebAuthenticationSession for the record, in case we want to get back to it.
This also fixes what I think were 3 related but separate bugs:
1. the getter for `NYPLUserAccount.authDefinition` could return a non null value even when we were signed out. For example, if the authentication document supported OAuthClientCredentials, the `hasOAuthClientCredentials()` function would return true in all cases, leading to think that we are signed in.
2. the signIn business logic updateUserAccount() method contained extra work that didn't belong there, and would result in confusing expectations
3. because saving on the keychain …
> OE-514 Clever authentication refactor

- Simplified.xcodeproj/project.pbxproj
bumps OE version to 2.5.1 to diagnose CI failures
IOS-433
n/a
n/a
y
n/a
@ettore
> Bump OE version

- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
The alert after deleting server data now shows Open eBooks instead of SimplyE
Bump version to 2.5.1
[OE-604](https://jira.nypl.org/browse/OE-604)
Log into Open eBooks
Go to 'Account' -> 'Delete Server Data'
After deleting server data, it should show an alert with Open eBooks name on it
N/A
Yes
N/A
@ErnestFan
> OE-604 Fix delete data wordings for OEB

- Simplified.xcodeproj/project.pbxproj
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
Use barcode/pin for request header when auth token is missing
[iOS-434](https://jira.nypl.org/browse/IOS-434)
See ticket
N/A
Yes
N/A
@ErnestFan
> iOS-434 Use barcode/pin for request header when auth token is missing

- Simplified.xcodeproj/project.pbxproj
- Simplified/AxisService/Download/NYPLAxisBookDownloadMediator.swift
- Simplified/AxisService/NYPLAxisServiceAdapter.swift
- Simplified/ErrorHandling/NYPLAlertUtils.swift
- Simplified/ErrorHandling/NYPLUserFriendlyError.swift
- Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Network/NYPLOAuthTokenRefresher.swift
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
- expand NYPLAlertUtils to be able to combine app-generated error messages with server (or network interaction) -generated errors
- surface errors in some My Books interactions (especially Axis downloads)
[IOS-179](https://jira.nypl.org/browse/IOS-179)
I will add some info in the ticket, although this might be hard to replicate
https://github.com/NYPL-Simplified/Axis-iOS/pull/20 needs to be merged beforehand
yes
yes
**Did someone actually …
> IOS-179 Surface book-downloading API errors

- Simplified.xcodeproj/project.pbxproj
- Simplified/Book/Models/NYPLBookRegistryRecord.h
- Simplified/Book/Models/NYPLBookRegistryRecord.m
- SimplifiedTests/Mocks/NYPLBookRegistryMock+Audiobooks.swift
- SimplifiedTests/NYPLAudiobookBookmarksBusinessLogicTests.swift
Implement unit tests for audiobook bookmark business logic
Update NYPLBookRegistryMock and NYPLBookRegistryRecord
[iOS-426](https://jira.nypl.org/browse/IOS-426)
Unit tests should be ran by CI
Will update the NYPLAudiobookToolkit commit ref once the other PR is merged
N/A
N/A
@ErnestFan
> iOS-426 Implement unit tests for audiobook bookmark and updated related classes

- Simplified.xcodeproj/project.pbxproj
- Simplified/Audiobooks/Bookmark/NYPLAudiobookBookmarksBusinessLogic.swift
- Simplified/Book/Models/NYPLBookRegistry.h
- Simplified/Book/Models/NYPLBookRegistry.m
- Simplified/Book/UI/NYPLBookCellDelegate+AudiobookBookmark.swift
- Simplified/Book/UI/NYPLBookCellDelegate+Audiobooks.m
- Simplified/en.lproj/Localizable.strings
- Simplified/it.lproj/Localizable.strings
- SimplifiedTests/NYPLAudiobookBookmarksBusinessLogicTests.swift
Integrate bookmark business logic into audiobook manager
Update NYPLAudiobookToolkit commit ref
Update localized strings
Update related unit tests
[iOS-424](https://jira.nypl.org/browse/IOS-424)
[iOS-425](https://jira.nypl.org/browse/IOS-425)
See ticket
Updated NYPLAudiobookToolkit
Yes
N/A
@ErnestFan
> iOS-425 Integrate audiobook bookmark business logic into audiobook manager

- Simplified.xcodeproj/project.pbxproj
- Simplified/Accounts/User/NYPLUserAccount.swift
- Simplified/AxisService/Download/NYPLAxisNetworkExecutor.swift
- Simplified/AxisService/Read/NYPLAxisBookReadingAdapter.swift
- Simplified/Book/UI/NYPLBookDetailViewController.m
- Simplified/Network/NYPLNetworkExecutor.swift
- Simplified/Network/NYPLNetworkResponder.swift
- Simplified/Network/NYPLOAuthTokenRefresher.swift
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionSynchronizer.swift
- Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisContentProtection.swift
- Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisProtectedAssetHandler.swift
- Simplified/Reader2/ReaderStackConfiguration/LibraryService.swift
- Simplified/Settings/NYPLSettingsAccountDetailViewController.m
- Simplified/SignInLogic/NYPLAccountSignInViewController.m
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogicUIDelegate.swift
- Simplified/SignInLogic/OELoginCleverHelper.swift
- Simplified/SignInLogic/OELoginFirstBookVC.swift
- SimplifiedTests/Mocks/NYPLSignInOutBusinessLogicUIDelegateMock.swift
Removes download logic dependency from class that opens an Axis book.
Other minor renames and cleanups.
[PJR-69](https://jira.nypl.org/browse/PJR-69)
no breaking changes, will be covered by regression.
This is dependent on https://github.com/NYPL-Simplified/Axis-iOS/pull/22 which should be merged first. I'll then need to update the commit ref for the Axis-iOS submodule.
no
yes …
> PJR-69 Remove download logic dependency from book opening logic

- Simplified/Book/UI/NYPLBookCellDelegate.m
- Simplified/Reader2/Bookmarks/NYPLAnnotations.swift
- Simplified/Settings/NYPLSettings.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+BookmarkSyncing.swift
- SimplifiedTests/Mocks/NYPLAnnotationsMock.swift
- Removes the NYPLSettings implicit dependencies from NYPLAnnotations.
- Removes the AccountsManager implicit dependencies from a couple methods in NYPLAnnotations.
[IOS-382](https://jira.nypl.org/browse/IOS-382)
regression will cover this.
no breaking changes
no
n/a
@ettore
> IOS-382 Remove some implicit dependencies in NYPLAnnotations

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NYPLRootTabBarController+Common.swift
- Simplified/AppInfrastructure/NYPLRootTabBarController.m
- Simplified/Book/UI/NYPLBookCellDelegate.m
- Simplified/Reader2/BusinessLogic/NYPLLastReadPositionSynchronizer.swift
- Simplified/Reader2/BusinessLogic/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/Networking/NYPLAnnotations.swift
- Simplified/Reader2/Networking/NYPLLastReadPositionPoster.swift
- Simplified/Reader2/Networking/NYPLLastReadPositionSynchronizer.swift
- Simplified/Reader2/ReaderPresentation/ReaderModule.swift
- Simplified/Reader2/ReaderPresentation/ReadingFormats/EPUBModule.swift
- Simplified/Reader2/ReaderStackConfiguration/NYPLR2Owner.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- Simplified/Reader2/UI/NYPLEPUBViewController.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+BookmarkSyncing.swift
- SimplifiedTests/Mocks/NYPLAnnotationsMock.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
Makes it so that the notion of NYPLAnnotations is not implicit inside the reader, but is injected at the entry point (NYPLR2Owner).
PJR-70
No breaking changes. A regression will cover this
n/a
no
yes
@ettore
> PJR-70 Dependency-inject NYPLAnnotations calls

- Simplified/Accounts/Library/Account.swift
- Simplified/Accounts/Library/AccountsManager.swift
- Simplified/Audiobooks/Bookmark/NYPLAudiobookBookmarksBusinessLogic.swift
- Simplified/Book/UI/NYPLBookCellDelegate+AudiobookBookmark.swift
- Simplified/Book/UI/NYPLBookCellDelegate.m
- Simplified/Reader2/BusinessLogic/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/ReaderPresentation/NYPLRootTabBarController+R2.swift
- Simplified/Reader2/ReaderPresentation/ReaderModule.swift
- Simplified/Reader2/ReaderPresentation/ReadingFormats/EPUBModule.swift
- Simplified/Reader2/ReaderPresentation/ReadingFormats/ReaderFormatModule.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- Simplified/Reader2/UI/NYPLEPUBViewController.swift
- SimplifiedTests/Mocks/NYPLLibraryAccountsProviderMock.swift
- SimplifiedTests/NYPLAudiobookBookmarksBusinessLogicTests.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
Removes the dependency on the AccountManager singleton from the reader classes. It turns out all it was needed was the flag to see if we had permission to sync bookmarks. So I just passed the flag in. 
Note that this solution assumes that this flag won't change while the reader is open, which is currently the case for SimpleE/OpenE and it seems like a reasonable assumption to me. However if you think this assumption is invalid, I have also implemented it by passing a protocol in instead. This alternative is implemented by the [1st commit](https://github.com/NYPL-Simplified/Simplified-iOS/commit/3c003f5c5229918c7bcb981317a52bb6ede2a70e). The 2nd checkin replaces the protocol with the direct flag value.  
Please let me know which solution you prefer.
**Why are we doing …
> PJR-86 Remove AccountManager implicit dependency from reader

- Simplified.xcodeproj/project.pbxproj
- Simplified/AppInfrastructure/NYPLRootTabBarController+Common.swift
- Simplified/AppInfrastructure/NYPLRootTabBarController.h
- Simplified/Audiobooks/Bookmark/NYPLAudiobookBookmarksBusinessLogic.swift
- Simplified/Book/UI/NYPLBookCellDelegate+AudiobookBookmark.swift
- Simplified/Book/UI/NYPLBookCellDelegate.m
- Simplified/Book/UI/NYPLEPUBOpener.swift
- Simplified/Reader2/BusinessLogic/NYPLReaderBookmarksBusinessLogic.swift
- Simplified/Reader2/Networking/NYPLAnnotations.swift
- Simplified/Reader2/Networking/NYPLLastReadPositionPoster.swift
- Simplified/Reader2/Networking/NYPLLastReadPositionSynchronizer.swift
- Simplified/Reader2/ReaderPresentation/ReaderModule.swift
- Simplified/Reader2/ReaderPresentation/ReadingFormats/EPUBModule.swift
- Simplified/Reader2/ReaderStackConfiguration/NYPLR2Owner.swift
- Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
- Simplified/Reader2/UI/NYPLEPUBViewController.swift
- Simplified/Settings/NYPLSettingsDeleteServerDataViewController.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic+BookmarkSyncing.swift
- Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
- SimplifiedTests/Mocks/NYPLAnnotationsMock.swift
- SimplifiedTests/NYPLAudiobookBookmarksBusinessLogicTests.swift
- SimplifiedTests/NYPLReaderBookmarksBusinessLogicTests.swift
- Remove NYPLNetworkExecutor dependency from NYPLAnnotations API
- Change the way NYPLAnnotations is used by making it a regular class so it can have its own related state (e.g. the `failFastExecutor` instance var)
- Split NYPLAnnotationSyncing protocol by making it more granular. This way downstream classes can refer to what they actually need. For example, NYPLLastReadPositionPoster only needs the API to update the last read position. NYPLSignInBusinessLogic only needs the api to check and update the sync toggle.
PJR-87
regression should cover this
no breaking changes
**Does this …
> PJR-87 Use NYPLAnnotations as a regular class & refactor related protocols

- Simplified/Network/NYPLNetworkQueue.swift
- Simplified/Reader2/Networking/NYPLAnnotations.swift
- Simplified/Reader2/ReaderStackConfiguration/LibraryService.swift
- Simplified/Reader2/ReaderStackConfiguration/NYPLR2Owner.swift
- Simplified/Reader2/UI/NYPLEPUBViewController.swift
The switch from `PublicationServer` to `GCDHTTPServer` in Readium 2.5.0 caused some regressions when browsing ePubs with VoiceOver:
- rendering issues while browsing (swift L/R) when scroll mode is not set
- no automatic scroll when continuous reading mode is enabled.
This silences the many deprecation warnings that are now emitted while still using the old PublicationServer.
It also fixes a few other Xcode 14.3 warnings.
https://jira.nypl.org/browse/IOS-578
You should not see any warnings, except for one in `LibraryService.swift`, which seems unavoidable.
n/a
**Does this include changes …
> IOS-578 Suppress Readium 2.5 PublicationServer deprecation warnings
