Simplified/NYPLRemoteViewController.m

Doubled timeout interval for the first page in catalog feeds

---

Simplified/NNYPLAnnotations.swift

replaced static url with circulationURL

removed static url for annotations

---

Simplified/NYPLSettingsAccountViewController.m

Now correctly dismisses after sign in under all use-cases.
Updated some UI to sign in screen.

Sign in (dismiss bug and UI updates)

---

Simplified/NYPLReaderReadiumView.m

fixes page progress and info not showing on iPad

---

Simplified/NYPLAccountSignInViewController.m
Simplified/NYPLCatalogNavigationController.m
Simplified/NYPLHoldsNavigationController.m
Simplified/NYPLMyBooksNavigationController.m
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/en.lproj/Localizable.strings

Accessibility audit for multi-library features added.

---

Simplified/NYPLCatalogNavigationController.m
Simplified/NYPLHoldsViewController.m
Simplified/NYPLMyBooksViewController.m
Simplified/NYPLRemoteViewController.m
Simplified/NYPLSettings.h
Simplified/Simplified-Info.plist

Disable Library Switcher while sync or reloads are happening.

---

Simplified/NYPLSettingsAccountDetailViewController.m

Missed one view controller when updating to localized string in table view cell.

Updated cell to localized string.

---

Simplified/NYPLCatalogNavigationController.m
Simplified/NYPLHoldsNavigationController.m
Simplified/NYPLMyBooksNavigationController.m
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/en.lproj/Localizable.strings

resolves #527 
- Better library account switching
- Removed 'About [Library]' in settings detail

Account switching #527

---

Simplified/NYPLAnnotations.swift
Simplified/NYPLCirculationAnalytics.swift

Updated based on discussion of offline queue and removing custom URLConfiguration. Also consolidating headers and authHeader parameters.

Networking in Annotations/Analytics: Refactored and optimized

---

Simplified/NYPLAccountSignInViewController.m
Simplified/NYPLSettingsAccountDetailViewController.m

Updated cell layout code to auto layout.

---

Simplified/NYPLWelcomeScreen.swift

Welcome Screen - removed account bug

---

Simplified/RemoteHTMLViewController.swift

creating this PR on behalf of @gioneill in order to generate a new TestFlight version 
fixed #585

Handle clicked links to open in external app (if possible)

---

Simplified/NYPLSettingsAccountsList.swift

Made table view cells dynamic in height for longer Library Descriptions. Ready to support DynamicType.
Fixes #564

Fixed truncated description labels

---

Simplified/NYPLSettingsAccountsList.swift

Refresh accounts list in tableview when a change has been made.

---

Simplified/RemoteHTMLViewController.swift

Now centered in view either in split view controller or full screen.
fixes #489

Added autolayout to activity indicator.

---

Simplified/NYPLReaderSettings.h
Simplified/NYPLReaderSettings.m
Simplified/NYPLReaderSettingsView.m

...Now 8 options making new largest size…(250 up from 200).
70; 80; 90; 100; 120; 150; 200; 250;
Fixes #560

Adding larger font size option

---

Simplified/NYPLReaderViewController.m

Adjustment to auto layout to center the book title.

Centered Book Title on wider screens.

---

Podfile

changed help stack branch to master

---

Simplified.xcodeproj/project.pbxproj
Simplified/ExtendedNavBarView.swift
Simplified/NYPLReaderTOCCell.h
Simplified/NYPLReaderTOCCell.m
Simplified/NYPLReaderTOCViewController.h
Simplified/NYPLReaderTOCViewController.m
Simplified/NYPLReaderViewController.m
Simplified/NYPLTOC.storyboard

Updates to table of contents table view (auto layout, dynamic rows, segmented control)
fixes #611

Bookmarks #605

---

Simplified/NYPLReaderReadiumView.m

Updating default in spineItemDict to title-cased localized string "Current Chapter".
fixes #357

Update footer label in reader for "Current Chapter"

---

Simplified/NYPLCatalogNavigationController.m

Updated UIAlert message

---

Simplified/NYPLBookRegistryRecord.h
Simplified/NYPLBookRegistryRecord.m
Simplified/NYPLReaderTOC.storyboard

adjusted number of lines in storyboard and fixed initial value of bookmarks

Local bookmarks #605

---

Simplified/NYPLBookDetailNormalView.m
Simplified/NYPLReaderViewController.m
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/NYPLSettingsPrimaryTableViewController.m
Simplified/en.lproj/Localizable.strings

- Added missing strings to Localizable.strings
- Removed spaces from strings that act as keys to NSLocalizedString
Might close #482 ?

Added missing localized strings

---

Simplified/Accounts.json
Simplified/en.lproj/Localizable.strings

Updates copy from SimplyE to "The SimplyE Collection"
- Welcome Screen
- Titles
- Settings
fixes #653

Updating name to SimplyE Collection

---

Simplified/Accounts.json

BPL support email was wrong.
fixes #662

Updating BPL support email.

---

Simplified/en.lproj/Localizable.strings

updating spelling error on first-time welcome screen
fixes #660

Spelling and grammar updates.

---

Simplified/Accounts.json
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/en.lproj/Localizable.strings

I think the title pretty much covers it...

Requested Copy Updates.

---

Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/NYPLSettingsSplitViewController.m

Replaced HelpStack token stubs with values added to APIKeys.swift

---

Simplified/NYPLConfiguration.h
Simplified/NYPLConfiguration.m

Moved Bugsnag Key into APIKeys.swift. Added version string to config.

---

Simplified.xcodeproj/project.pbxproj
Simplified/Simplified-Info.plist

Updating DEBUG state for compiler when archiving for release..

Updated preprocessor flag for DEBUG. Updated version/build.

---

Simplified/Accounts.json

The reservations tab should be available for Montgomery

Allow reservations for Montgomery

---

Simplified/NYPLReaderReadiumView.m

@winniequinn After careful pruning of Develop branch, in preparation for deprecation, I came across this merge which never made it to master and was never released to production.
I don't remember if this was fully reviewed/tested/cleared or not.

External link handling in Reader

---

Simplified/Accounts.json

Adds the email address for Howard County support in iOS.

Add support email for Howard

---

Simplified/Accounts.json

Adds the support email for Montgomery County in the iOS client.

Add Montgomery support email

---

Simplified/NYPLBookDetailTableView.swift
Simplified/NYPLCatalogGroupedFeedViewController.m
Simplified/NYPLCatalogUngroupedFeedViewController.m
Simplified/NYPLMyBooksViewController.m

Improving layout of UIScrollView based on the new concept of "safe areas" means that I needed to audit some classes that were modifying content insets in the layout phases.
fixes #708

Ios11 content inset#708

---

Simplified/NYPLAccount.m
Simplified/NYPLAccountSignInViewController.m
Simplified/NYPLSettings.m

Under worst case scenario of broken keychains, this adds some UX and under-the-hood improvements to help ease the transition to sign back in for users.
resolves #730

Keychain migration improvements#730

---

Simplified/NYPLBookNormalCell.h
Simplified/NYPLBookNormalCell.m
Simplified/NYPLCatalogGroupedFeedViewController.m
Simplified/NYPLCatalogLaneCell.h
Simplified/NYPLCatalogUngroupedFeedViewController.m

Basic 3D touch functionality (iPhone 6S/Plus, iPhone 7/Plus, future models)
resolves #740

Implement basic 3D touch - peek/pop in catalog feed views

---

Simplified/NYPLAccountSignInViewController.m
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/NYPL_Launch_Screen.xib

More changes to support iOS 11 and consolidate UX in applicable areas.

iOS11 signin updates

---

Simplified/Accounts.json

Adds an email address for patrons to email for support at Frederick County.

Add support email for Frederick County

---

Simplified/NYPLAccountSignInViewController.m
Simplified/NYPLKeychain.h
Simplified/NYPLKeychain.m
Simplified/NYPLKeychainManager.swift

Updates to keychain migration. Copies then deletes keychain items from old to new. Handles re-authorizing of a user with those saved credentials (during read, get, or download).
resolves #745

Keychain grouping #745

---

Simplified/NYPLAccountSignInViewController.m
Simplified/NYPLSettingsAccountDetailViewController.m

Improved support for dynamic type and preventing chopped off text on registration cell when going extra large.
Full dynamic type support now on both sign in screens.
Fixes #754

Dynamic Type / Layout Updates (Sign In Screens)

---

Simplified/NYPLMyBooksDownloadCenter.m
Simplified/NYPLReaderReadiumView.m

located in metadata collected for bugsnag reports.
fixes #769

Protect against possible nil value in NSDictionaries

---

Simplified/NYPLSettingsAccountDetailViewController.m

fixes #755 
Fixing mistake and also adding extra info for logging.
Turns out there was a mistake in my original implementation that kept the flow from reaching a point where it lets the user sign out. So now we're back to letting a user sign out if the credentials have unexpectedly changed, which would (most likely) occur when a user changed their PIN, but has also been rearing itself in frequent beta testing between different builds of the app.

Correct logout flow for times when credentials may have changed.

---

Simplified/NYPLBookDetailTableView.swift

...In the Book Detail sections for books. Should gracefully remove itself under any unexpected failure of the feed or link.
fixes #753

Add activity indicator while related book lanes load for more clarity.

---

Simplified/Accounts.json
Simplified/NYPLConfiguration.m

update HEX color conversion for parity between platforms.
Accounts.json file should now be completely transportable between either platform. And even if libraries get added or removed, the client should handle this transition seamlessly.

Re-add Library JSON attributes for passcode type and options,

---

Simplified/NYPLMyBooksDownloadCenter.m
Simplified/NYPLSettingsAccountDetailViewController.m

Fix Bugsnag errors:
- nil crash on uialertcontroller setup
- nil crash on download a book
- added metadata for extra data gathering
fixes #704

Bug fixes #704

---

Simplified/NYPLCatalogNavigationController.m
Simplified/NYPLHoldsNavigationController.m
Simplified/NYPLMyBooksNavigationController.m

which can occur frequently between beta builds with different libraries.
fixes #786

Prevent crash when trying to switch to account that no longer exists

---

Simplified/NYPLReaderReadiumView.m

Fix undesired reflow on iOS 11 status bar toggle

---

Simplified/Accounts.json

Updates Alameda County's support email address.

Update Alameda County's support email

---

Simplified/NYPLReaderReadiumView.m
Simplified/NYPLReaderViewController.m
Simplified/NYPLTOC.storyboard

Add safe area padding and some inescapable hard-coded padding for iPhone X.

iPhone X Layout Adjustments

---

Simplified/Accounts.json

Updates their entry in Accounts.json with the current information.

Update Allegany County content license link

---

Simplified/NYPLReaderReadiumView.m

Fix crash when adding bookmark without CFI/idref

---

Simplified/NYPLAnnotations.swift
Simplified/NYPLBookCellDelegate.m
Simplified/NYPLCatalogGroupedFeedViewController.m
Simplified/NYPLCirculationAnalytics.swift
Simplified/NYPLReaderReadiumView.m
Simplified/NYPLReaderTOCViewController.m
Simplified/NYPLReadiumViewSyncManager.h
Simplified/NYPLReadiumViewSyncManager.m
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/NYPLSettingsAdvancedViewController.swift

Sync Logic Fix:
- Allows Sync switch to accurately reflect user's intention. Handle poor or no internet connection logic better.
fixes #874
Bugnsag:
fixes #873 
fixes #872 
fixes #871 
fixes #870

Sync Feature bug fixes

---

Simplified/NYPLAnnotations.swift
Simplified/NYPLBookRegistry.h
Simplified/NYPLBookRegistry.m
Simplified/NYPLConfiguration.h
Simplified/NYPLConfiguration.m
Simplified/NYPLReaderReadiumView.h
Simplified/NYPLReaderReadiumView.m
Simplified/NYPLReaderViewController.m
Simplified/NYPLReadiumViewSyncManager.h
Simplified/NYPLReadiumViewSyncManager.m
Simplified/Simplified-Info.plist

Mostly just some cleanup done while trying to find the cause of a larger issue present in the Sync feature.
- Renamed some methods and variables
- Got rid of unused protocol methods
- Added some missing completion handler calls to ensure correct sync logic
- Updated Bugsnag config (Resolves #887 )

Sync Feature - Maintenance Refactoring and Cleanup

---

Simplified/NYPLBookDetailViewController.m

Fix Book Detail Problem Report VC to Dismiss after submission

---

Simplified.xcodeproj/project.pbxproj
Simplified/NYPLBookAcquisitionPath.m
Simplified/NYPLMyBooksDownloadCenter.m
Simplified/NYPLMyBooksDownloadInfo.h
Simplified/NYPLMyBooksSimplifiedBearerToken.h
Simplified/NYPLMyBooksSimplifiedBearerToken.m

Add bearer token authentication

---

Simplified/NYPLMyBooksDownloadCenter.m

Handle redirects when using bearer tokens

---

Simplified/Simplified.js

Grab me if you want an explanation for this one.

Show OpenDyslexic fonts in the reader webview

---

Simplified/NYPLReadiumViewSyncManager.m

fixes #952 
Addresses top bugnsag crash on a missed nil-check, and updates strings in Sync Alert Controller message.

Syncmanager nil check 952

---

Simplified/Simplified-Info.plist

resolves #845 
refer to ticket for explanation.

Update PLIST Key for adding photos to user's library

---

Simplified/NYPLBookButtonsView.m

Reverts NYPL-Simplified/Simplified-iOS#961

Revert "Update rounded button view to show time remaining"

---

Simplified/Accounts.swift
Simplified/NYPLSettingsAccountsList.swift

This is a very small change to sort the list of libraries when adding a new library. It also changes the add button title from "+" to the harder-to-miss "Add Library".

Sort libraries when adding; emphasize add button

---

Simplified/NYPLConfiguration.m
Simplified/NYPLNetworkQueue.swift
Simplified/NYPLReaderTOCViewController.m

Addressed two highest-rated crashes in Bugsnag, not related to crash that occurs on manual app termination.

Crash/Bug fixes from Analytics

---

Simplified/NYPLOPDSFeed.m

Co-authored-by: Greg O'Neill <gioneill@gmail.com>

Fix crash on invalid feed

---

README.md

Add ReaderClientCert.sig note to README.md

---

Simplified/NYPLMyBooksViewController.m

This issue only affected devices running iOS 11 or later.

Fix inability to scroll to bottom of My Books

---

Simplified.xcodeproj/project.pbxproj
Simplified/NYPLReaderReadiumView.m
Simplified/Simplified.js

This fixes the following:
* Long-load detection failing to notice when a page is ready
* Page transitions not working correctly
* Tap-to-turn only working at the very edges of the screen
* Navigation toggling not working
* OpenDyslexic typeface selection not working
* Link-time failures

Support iOS 12

---

Simplified/NSDate+NYPLDateAdditions.h
Simplified/NSDate+NYPLDateAdditions.m
Simplified/NYPLOPDSEntry.m

This PR addresses the JIRA issue: https://jira.nypl.org/browse/SIMPLY-735
by setting the published date with the value from dc:issued instead of atom:published

Set Publication Date from dc:issued #735

---

Simplified/NYPLAppDelegate.m
Simplified/NYPLUserNotifications.swift

Also increase minimum fetch interval to 24 hours.

Tweak polling to decrease unneeded background fetches over the network.

---

.gitignore
Simplified.xcodeproj/project.pbxproj
Simplified/NYPLMyBooksDownloadCenter.m
SimplifiedTests/NYPLMyBooksDownloadCenterTests.swift

Currently there's no switch option for deleting PDF books. This is a simple copy-pasta for the EPUB case.

[SIMPLY-1952] Ensure PDFs get deleted

---

Simplified/NYPLPDFViewControllerDelegate.swift

Fixed PDFs not being marked as read

---

Simplified/NYPLBookCoverRegistry.m
Simplified/NYPLDirectoryManager.swift
Simplified/NYPLMyBooksDownloadCenter.m
Simplified/Simplified-Info.plist

Hotfix for null account

---

Simplified/NYPLAccountSignInViewController.m

Deferring UI-modifying code to main thread

Fixing threading problem for UI

---

pull_request_template.md

This added a template that is pre-populated with each pull request.
Improve the efficiency and usefulness of code reviews.
No tests
No dependencies 
Not yet, we should probably add this somewhere in the dev docs
@MalcolmMcFly

Added new pull request template

---

.gitignore
README.md
Simplified.xcodeproj/project.pbxproj
Simplified/NYPLSecrets.swift
build-3rd-parties-dependencies.sh

Add a NYPLSecrets.swift with variables and functions declaration without actual details
Update README with instruction to generate keys into NYPLSecrets.swift
[SIMPLY-2655](https://jira.nypl.org/browse/SIMPLY-2655)
Update your local Certificates repo, follow the fourth step of `Building the application` in README
Please also see if the difference in NYPLSecrets is untracked in git after running the script
No
Updated build instruction
@ErnestFan

SIMPLY-2655 Secure secrets loading systems

---

Simplified/NYPLSecrets.swift

Minor change:
- make enum case iterable
- decode function is now private
Security and enum usage
Not needed
No
No
@ErnestFan

Make enum case iterable and decode private

---

Simplified/Utilities/Authentication/NYPLUserAccountFrontEndValidation.m

Add range check to avoid out of bound
[SIMPLY-2987](https://jira.nypl.org/projects/SIMPLY/issues/SIMPLY-2987)
Unable to reproduce issue
N/A
N/A
@ErnestFan

SIMPLY-2987 Add range check to avoid out of bound

---

Simplified/NYPLErrorLogger.swift

This just moves related logging methods together for ease of searching / browsing.  There are no functional changes here.
This could have been part of PR #1172 but it would have hidden the real changes from the purely cosmetic ones. By separating it in 2 PRs code review is a lot simpler.
https://jira.nypl.org/browse/SIMPLY-2992
No QA needed.
none
n/a
@ettore

SIMPLY-2992 Group related log methods together

---

Simplified/NYPLReadiumViewSyncManager.m

Move UI related code into main thread to avoid crash
https://jira.nypl.org/browse/SIMPLY-3016
N/A
N/A
No
@ErnestFan

SIMPLY-3016 Fix UIAlertController not init in main thread

---

Simplified/Network/NYPLNetworkResponder.swift

This code might be easier to review by looking at the individual commits.
The 1st commit fixes the fact that we were returning (in a network call) the error that can occur in parsing of problem document instead of the actual network error. The parse error was just meant to be logged and the user has no interest in it.
The 1st commit also renames the "error" variables for clearer semantics.
The 2nd commit just refactors that code in a separate function since the original one was getting out of hand as far as length goes.
Fixing / improving error reporting. Saw this while working on SIMPLY-3179
The same steps of SIMPLY-3179 apply, and the rest …

Don't pass problem document parse errors to callers: just log them

---

Simplified.xcodeproj/project.pbxproj
Simplified.xcodeproj/xcshareddata/xcbaselines/2D2B47711D08F807007F7764.xcbaseline/48147671-1068-4568-BF8F-A63B52826650.plist
Simplified/NYPLSettingsAccountDetailViewController.m
Simplified/Settings/NYPLSettings.swift
Simplified/SignInLogic/NYPLAccountSignInViewController+OESelectAuth.swift
Simplified/SignInLogic/NYPLAccountSignInViewController.m
Simplified/SignInLogic/NYPLSignInBusinessLogic+BookmarkSyncing.swift
Simplified/SignInLogic/NYPLSignInBusinessLogic+CardCreation.swift
Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
SimplifiedTests/Mocks/NYPLURLSettingsProviderMock.swift

This PR is just moving methods around so that they are grouped together more logically. There are no "real" code changes beside fixing the OE build (that's isolated in commit 59aa144).
https://jira.nypl.org/browse/SIMPLY-2510
will add steps in ticket
n/a
yes
@ettore

SIMPLY-2510 Group related methods together in sign-in view controllers

---

.github/workflows/unit-testing.yml
README.md
Simplified.xcodeproj/project.pbxproj

Also adds badges to the repo README and remove some cruft from workflow.
improve documentation
n/a
n/a
n/a
@ettore

Update README and build numbers

---

Simplified.xcodeproj/project.pbxproj
Simplified/Reader2/UI/NYPLBaseReaderViewController.swift
scripts/build-carthage-R2-integration.sh

Include chapter title in reader footer
Fix build script for R2 dev
[SIMPLY-705](https://jira.nypl.org/browse/SIMPLY-705)
Make sure R2 is on in developer setting menu
Open any book except audiobook
The footer in the reader should show the current location in the format of `Page x of x (Chapter Title)`
The chapter title is only shown when it's available
N/A
N/A
N/A
@ErnestFan

SIMPLY-705 Improvement to Reader Page + Location in footer

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisService.swift
Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Simplified/MyBooks/NYPLMyBooksDownloadInfo.h
Simplified/OPDS/NYPLOPDSAcquisitionPath.h
Simplified/OPDS/NYPLOPDSAcquisitionPath.m

Basic Setup to allow Axis DRM content
Axis DRM
Can not be tested as of yet.
N/A
N/A
N/A
Raman Singh verified it.

Basic setup to allow Axis DRM content

---

Simplified.xcodeproj/project.pbxproj
Simplified/Accounts/Library/AccountsManager.swift
Simplified/AppInfrastructure/NYPLBookContentMetadataFilesHelper.swift
Simplified/LibraryFinder/NYPLLibraryFinderBusinessLogic.swift
Simplified/LibraryFinder/NYPLLibraryFinderConfiguration.swift
Simplified/LibraryFinder/UI/NYPLLibraryFinderLibraryCell.swift
Simplified/LibraryFinder/UI/NYPLLibraryFinderSectionFooterView.swift
Simplified/LibraryFinder/UI/NYPLLibraryFinderSectionHeaderView.swift
Simplified/LibraryFinder/UI/NYPLLibraryFinderViewController.swift
Simplified/Settings/NYPLSettings+SE.swift
Simplified/Settings/NYPLSettingsAccountsList.swift
Simplified/Utilities/Strings/Stringable.swift
Simplified/Utilities/UI/CALayer+CustomBorder.swift
Simplified/WelcomeScreen/NYPLWelcomeScreenViewController.swift
Simplified/en.lproj/Localizable.strings
Simplified/it.lproj/Localizable.strings

Implement the Finder UI
[iOS-99](https://jira.nypl.org/browse/IOS-99)
[figma](https://www.figma.com/file/cN3JQg2twdBocvNenixBaY/SimplyE%3A-Finder?node-id=652%3A1606)
Not ready to be tested
N/A
No
No
@ErnestFan

Implement Library Finder UI and business logic

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisContentDownloader.swift
Simplified/AxisService/NYPLAxisNetworkExecuting.swift
Simplified/AxisService/NYPLAxisNetworkExecutor.swift
Simplified/AxisService/NYPLAxisService.swift
SimplifiedTests/NYPLContentDownloaderTests.swift

Creates a downloader responsible for downloading Axis content
https://jira.nypl.org/browse/OE-62
This cannot be thoroughly tested by front-end QA. If you're able to download an axis book, it means it's working. Also, additional Unit tests have been written.
N/A
N/A
N/A

OE-62: Created a downloader responsible for downloading Axis content

---

Simplified/Book/UI/NYPLBookCellDelegate.m

this crash is caused by an unrecognized message sent to an invalid `DefaultAudiobookManager` instance. While the class has some possible threading issues, I don't think they are the cause of this crash, because the incriminated `manager` property is being deallocated as part of the timer behavior (which appears correct to me). However, at the point of crash we were accessing the lower level pointer instead of the property, and the property was not `atomic`, so it is possible (depending on the optimizations done by the runtime) to access a garbage pointer. By using `atomic` and the property we should avoid this situation.
If the crash persists, I think it will be time (no pun intended 😄 ) for a larger refactor (ensuring thread safety, perhaps avoiding the timer …

IOS-190 Access property via accessor to ensure consistency

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisContentDownloader.swift
Simplified/AxisService/NYPLAxisItemDownloader.swift
Simplified/AxisService/NYPLAxisKeysProvider.swift
Simplified/AxisService/NYPLAxisLicenseService.swift
Simplified/AxisService/NYPLAxisMetadataService.swift
Simplified/AxisService/NYPLAxisPackageService.swift
Simplified/AxisService/NYPLAxisService.swift
Simplified/AxisService/NYPLRSACypher.swift
Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
SimplifiedTests/NYPLContentDownloaderTests.swift

Prepares book download code to accommodate  decryption of Axis book content
https://jira.nypl.org/browse/OE-14
User should be able to open Axis books
N/A
Will do after adding tests
N/A

OE-14: Decrypt book content with Axis DRM

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisItemDownloader.swift
SimplifiedTests/NYPLAxisTests/AssetWriterMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisContentDownloaderMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisItemDownloaderTests.swift
SimplifiedTests/NYPLAxisTests/NYPLContentDownloaderTests.swift
SimplifiedTests/NYPLAxisTests/TerminationListenerMock.swift

Adds tests for NYPLAxisItemDownloader
N/A
N/A
N/A
N/A

Wrote tests for NYPLAxisItemDownloader

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisLicenseService.swift
Simplified/AxisService/NYPLAxisService.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisBookDownloadBroadcasterMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisLicenseServiceMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisMetadataServiceMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisPackageServiceMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisServiceTests.swift
SimplifiedTests/NYPLAxisTests/NYPLDownloadRunnerMock.swift

Adds tests for NYPLAxisService
N/A
N/A
N/A
N/A

NYPL Axis Service Tests

---

Simplified.xcodeproj/project.pbxproj
SimplifiedTests/NYPLAxisTests/NYPLAxisXMLTests/DummyCatalog.xml
SimplifiedTests/NYPLAxisTests/NYPLAxisXMLTests/NYPLAxisXMLTests.swift

Adds tests for NYPLAxisXML
N/A
N/A
N/A
N/A

Wrote tests for NYPLAxisXML

---

Simplified.xcodeproj/project.pbxproj
SimplifiedTests/NYPLAxisTests/NYPLAxisItemDownloaderTests.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisMetadataServiceTests.swift

Adds tests for Metadata Service
N/A
N/A
N/A
N/A

Wrote tests for Metadata Service

---

Simplified.xcodeproj/project.pbxproj
Simplified/Book/UI/NYPLBookCellDelegate.m
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisContentDecryptor.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisContentProtection.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisLibraryService.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisProtectedAssetHandler.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLFullAxisNowResource.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLZlibDecompressor.swift
Simplified/Reader2/ReaderStackConfiguration/LibraryService.swift
Simplified/Settings/NYPLSettings.swift

Allows user to open Axis Book Content
https://jira.nypl.org/browse/OE-14
Downloaded Axis book should open for reading
N/A
N/A
N/A

OE-14: Added code for reading book content

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisDownloadProgress.swift
Simplified/AxisService/NYPLAxisItemDownloader.swift
SimplifiedTests/NYPLAxisTests/Mocks/NYPLAxisDownloadTaskWeightProviderMock.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisDownloadProgressTests.swift
SimplifiedTests/NYPLAxisTests/NYPLAxisItemDownloaderTests.swift

Adds tests for NYPLAxisDownloadProgress
Testing purposes
N/A
N/A
N/A

Wrote tests for DownloadTaskProgress

---

Simplified/AxisService/NYPLAxisDownloadProgress.swift

Fixes Axis book download starting at 100%
https://jira.nypl.org/browse/OE-143
Follow the steps in the ticket
N/A
Not yet
N/A

OE-143: Fix Axis book download starting at 100%

---

Simplified.xcodeproj/project.pbxproj
Simplified/AxisService/NYPLAxisPackagePathPrefixProvider.swift
SimplifiedTests/NYPLPackagePathPrefixProviderTests.swift

Fixes some axis books failing to download
https://jira.nypl.org/browse/OE-141
Follow the steps in the tickets
N/A
N/A
N/A

OE-141: Fix some axis books failing download

---

.github/workflows/archive-and-upload.yml
.github/workflows/unit-testing.yml
.gitignore
Simplified.xcodeproj/project.pbxproj
Simplified.xcodeproj/xcshareddata/xcschemes/Open eBooks.xcscheme
Simplified/AxisService/Download/NYPLAxisBookDownloadMediator.swift
Simplified/AxisService/Download/NYPLAxisContentDownloader.swift
Simplified/AxisService/Download/NYPLAxisDRMAuthorizer.swift
Simplified/AxisService/Download/NYPLAxisNetworkExecutor.swift
Simplified/AxisService/NYPLAxisServiceAdapter.swift
Simplified/AxisService/Read/NYPLAxisBookContentDecryptionAdapter.swift
Simplified/AxisService/Read/NYPLAxisBookReadingAdapter.swift
Simplified/AxisService/Read/NYPLAxisDecompressionAdapter.swift
Simplified/AxisService/Read/NYPLFullAxisNowResourceAdapter.swift
Simplified/AxisService/Utilities/NYPLAxisErrorLogsAdapter.swift
Simplified/AxisService/Utilities/NYPLAxisXMLCreator.swift
Simplified/AxisService/Utilities/NYPLAxisXMLRepresentation.swift
Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisContentDecryptor.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisContentProtection.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisDecompressor.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisLibraryService.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisProtectedAssetHandler.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLFullAxisNowResource.swift
Simplified/Reader2/ReaderStackConfiguration/LibraryService.swift
scripts/build-carthage.sh
scripts/buildNYPLAxis.sh

Adds adapters for using NYPLAxis framework for reading/downloading an Axis book
https://jira.nypl.org/browse/OE-154
Axis book should be able to be downloaded and read
N/A
Not yet
N/A

OE-154: Conclude Axis DRM

---

Simplified.xcodeproj/project.pbxproj
SimplifiedTests/NYPLAxisTests/NYPLAxisXMLTests/DummyCatalog.xml
SimplifiedTests/NYPLAxisTests/NYPLAxisXMLTests/NYPLAxisXMLTests.swift
scripts/buildNYPLAxis.sh

Adds missing tests for NYPLAxisXML and fixes Axis-iOS pointing to develop
https://jira.nypl.org/browse/OE-154
Can not be QA tested since the changes are related to building and unit tests
N/A
N/A
N/A

OE-154: Added missing tests for NYPLAxisXML and fixed Axis-iOS pointing to develop

---

Simplified.xcodeproj/project.pbxproj

[Description of what this PR does goes here]
[Quick blurb about why the code is needed and Jira link goes here / Do these changes meet the business requirements of the story?]
[Description of any tests that need to be performed once merged goes here]
[Description of any watchouts, dependencies, or issues we should be aware of goes here]
[Bump the SimplyE build number to generate a new build on NYPL-Simplified/iOS-binaries]
**Did someone actually run …

Test bumping OE build number

---

Simplified/Book/Models/NYPLBookCoverRegistry.m

Add nil check for UrlPathComponent to avoid crash
[iOS-228](https://jira.nypl.org/browse/IOS-228)
N/A
N/A
N/A
N/A
@ErnestFan

iOS-228 Add nil check for UrlPathComponent

---

Simplified/AxisService/Read/NYPLAxisBookReadingAdapter.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisContentProtection.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisLibraryService.swift
Simplified/Reader2/ReaderStackConfiguration/Axis/NYPLAxisProtectedAssetHandler.swift
Simplified/Reader2/ReaderStackConfiguration/LibraryService.swift

Renames a few functions for clarity and improves docs. No changes of behavior are intended!
Some motivations behind some choices in the license and book download process for Open eBooks were not clear to me from the current code and docs.
a regression will cover these changes.
Dependent on https://github.com/NYPL-Simplified/Axis-iOS/pull/5
no
yes
@ettore

OE-187 Improve code clarity + docs regarding download process

---

Cartfile
Cartfile.resolved
Simplified/Settings/NYPLSettingsAccountDetailViewController.m
Simplified/SignInLogic/NYPLAccountSignInViewController.m
Simplified/SignInLogic/NYPLSignInBusinessLogic+CardCreation.swift
Simplified/SignInLogic/NYPLSignInBusinessLogic.swift
Simplified/en.lproj/Localizable.strings
Simplified/it.lproj/Localizable.strings

Update sign-up logic for new CardCreation API
[iOS-232](https://jira.nypl.org/browse/IOS-232)
We should do regression testing on the whole CardCreation process
Need to merge in CardCreator branch after QA approval and update the reference
Not yet
No
@ErnestFan

iOS-232 Update sign-up logic for new CardCreation API

---

Simplified/Book/UI/NYPLBookButtonsView.m
Simplified/Book/UI/NYPLBookDetailDownloadFailedView.m
Simplified/Book/UI/NYPLBookDetailDownloadingView.m
Simplified/Book/UI/NYPLBookDetailView.m
Simplified/Book/UI/NYPLBookDetailsProblemDocumentViewController.swift
Simplified/Book/UI/NYPLBookDownloadingCell.m
Simplified/Catalog/NYPLContentTypeBadge.swift
Simplified/Holds/NYPLHoldsViewController.m
Simplified/Settings/NYPLSettingsAccountDetailViewController.m
Simplified/SignInLogic/NYPLAccountSignInViewController.m
Simplified/WelcomeScreen/OETutorialViewController.swift
scripts/build-dependencies.sh

Fix crash in settings tab while updating colors
Fix typo in build script
[iOS-288](https://jira.nypl.org/browse/IOS-288)
See test step in ticket's comment section
N/A
N/A
N/A
@ErnestFan

iOS-288 Fix crash in settings tab while updating colors

---

.github/workflows/archive-and-upload.yml
Gemfile

Cherry-picked the commits that needed for the fastlane fix we done on release branch
N/A
N/A
N/A
N/A
N/A
@ErnestFan

Merge fastlane CI fix for SimplyE 3.8.5 into develop

---

Simplified/MyBooks/NYPLMyBooksDownloadCenter.m
Simplified/MyBooks/NYPLMyBooksDownloadInfo.h

Add some comments after looking at the MyBooks code more in-depth, and a minor simplification in adept fulfillment callback.
Trying to simplify the logic before the rewrite.
a regression will cover this.
n/a
no
yes
@ettore

IOS-397 Minor simplifications for clarity

---

Simplified/MyBooks/NYPLMyBooksDownloadCenter.m

Moving some methods around in MyBooksDownloadCenter with the intent to make the code easier to browse. There's are no changes in functionality at all.
This is how it looks now:
IOS-397 
n/a
n/a
no
yes
@ettore

IOS-397 Re-org methods, no functionality changes

---

Simplified.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Update dependencies with the latest changes on NYPLUtilities
[ios-393](https://jira.nypl.org/browse/IOS-393)
N/A
Updated
N/A
N/A
@ErnestFan

iOS-393 Update dependencies git ref for NYPLUtilities changes

---

README.md
scripts/bootstrap-drm.sh

improves docs
reviewing docs before start of new hire.
n/a
n/a
nah
yes
@ettore

Improve build documentation
